> **Kaggle Notebook** — Run this notebook on Kaggle with a GPU accelerator.
> 
> ⚙️ **Required:** Go to *Notebook Settings → Internet* and enable **Internet access**
> so that `git clone` and Hugging Face Hub downloads work correctly.

# Adaptive Data Selection & Curriculum Learning for Compute-Efficient LLM Fine-Tuning
## Cloud GPU Execution & Experiment Orchestration Notebook

This notebook orchestrates the complete 2×2 experiment matrix and ablations on a Kaggle GPU instance:

| Exp | Selection | Ordering | Description |
|:---|:---|:---|:---|
| **E1** | 100% (Full) | Random | Baseline (all 49.4k training examples) |
| **E2** | Random 50% | Random | Uniform random subsampling |
| **E3** | Adaptive 50% | Random | Importance-scored selection (Diversity + Complexity + Length) |
| **E4** | Adaptive 50% | Curriculum | **Full Method** (Adaptive Selection + Easy→Hard Curriculum) |
| **E5** | Random 50% | Curriculum | Curriculum on random subset (Isolation test) |
| **Ablation A** | Adaptive 50% | Random | Diversity score only |
| **Ablation B** | Adaptive 50% | Random | Complexity score only |

**Hardware Target:** 1× NVIDIA GPU with $\ge$ 6–16 GB VRAM (e.g., T4, A100, RTX 3090/4090, L4).

In [5]:
# ── Clone repository (requires Internet enabled in Notebook Settings) ────────
import subprocess, sys

# Quick connectivity check before cloning
result = subprocess.run(["curl", "-s", "--max-time", "5", "https://github.com"],
                        capture_output=True)
if result.returncode != 0:
    print("ERROR: Cannot reach github.com.")
    print("  → Go to Notebook Settings (right sidebar) → Internet → turn ON, then re-run.")
    sys.exit(1)

!git clone https://github.com/Bezawit-cloud/efficient-llm-finetuning.git
%cd efficient-llm-finetuning

Cloning into 'efficient-llm-finetuning'...
remote: Enumerating objects: 126, done.
remote: Counting objects: 100% (126/126), done.
remote: Compressing objects: 100% (85/85), done.
remote: Total 126 (delta 66), reused 81 (delta 29), pack-reused 0 (from 0)
Receiving objects: 100% (126/126), 59.23 KiB | 14.81 MiB/s, done.
Resolving deltas: 100% (66/66), done.
/kaggle/working/efficient-llm-finetuning/efficient-llm-finetuning/efficient-llm-finetuning

In [6]:
# ── Kaggle: Load HF token & set memory allocator env vars ──────────────────
import os

# Load HuggingFace token from Kaggle Secrets (add secret named 'HF_TOKEN' in
# Notebook Settings → Secrets before running)
try:
    from kaggle_secrets import UserSecretsClient
    _secrets = UserSecretsClient()
    os.environ["HF_TOKEN"] = _secrets.get_secret("HF_TOKEN")
    print("HF_TOKEN loaded from Kaggle Secrets.")
except Exception as e:
    print(f"[WARN] Could not load HF_TOKEN from Kaggle Secrets: {e}")
    print("       Set os.environ['HF_TOKEN'] manually if Hub rate-limiting occurs.")

# Expandable CUDA segments — avoids fragmentation OOM on T4
# (also set inside train_baseline.py and gpu_smoke_test.py as a safety net)
os.environ.setdefault("PYTORCH_CUDA_ALLOC_CONF", "expandable_segments:True")
print(f"PYTORCH_CUDA_ALLOC_CONF = {os.environ['PYTORCH_CUDA_ALLOC_CONF']}")

# All outputs will persist under /kaggle/working/
WORK_DIR = "/kaggle/working/efficient-llm-finetuning"
print(f"Working directory: {WORK_DIR}")

[WARN] Could not load HF_TOKEN from Kaggle Secrets: Unexpected response from the service. Response: {'errors': ['No user secrets exist for kernel id 131400071 and label HF_TOKEN.'], 'error': {'code': 5}, 'wasSuccessful': False}.
       Set os.environ['HF_TOKEN'] manually if Hub rate-limiting occurs.
PYTORCH_CUDA_ALLOC_CONF = expandable_segments:True
Working directory: /kaggle/working/efficient-llm-finetuning

### Step 1: Environment & GPU Verification

In [7]:
# Verify GPU hardware
!nvidia-smi

import torch
print(f"PyTorch: {torch.__version__}")
print(f"CUDA Available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")
    print(f"VRAM: {torch.cuda.get_device_properties(0).total_memory / (1024**3):.2f} GB")
    print(f"BF16 Support: {torch.cuda.is_bf16_supported()}")

Fri Aug 21 00:02:27 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.159.04             Driver Version: 580.159.04     CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   52C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  Tesla T4                       Off |   00000000:00:05.0 Off |                    0 |
| N/A   40C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
PyTorch: 2.10.0+cu128
CUDA Available: True
GPU: Tesla T4
VRAM: 14.56 GB
BF16 Support: True

### Step 2: Install Dependencies

In [8]:
# Install repository requirements
%pip install -r requirements.txt -q

Note: you may need to restart the kernel to use updated packages.

### Step 3: Run GPU Smoke Test
Verifies CUDA detection, Qwen2.5-0.5B loading, LoRA parameter attachment, 1 step execution, and peak memory logging.

In [9]:
!python src/gpu_smoke_test.py

Skipping import of cpp extensions due to incompatible torch version. Please upgrade to torch >= 2.11.0 (found 2.10.0+cu128).
=================================================================
GPU MIGRATION SMOKE TEST — QWEN2.5-0.5B-INSTRUCT
=================================================================
PyTorch Version:     2.10.0+cu128
CUDA Available:      True
Active Device:       cuda (Tesla T4)
Total GPU VRAM:      14.56 GB
CUDA Version:        12.8
BF16 Supported:      True
-----------------------------------------------------------------
Loading Tokenizer:   Qwen/Qwen2.5-0.5B-Instruct ...
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Map: 100%|█████████████████████████████| 32/32 [00:00<00:00, 3780.67 examples/s]
Loading Model:       Qwen/Qwen2.5-0.5B-Instruct on cuda ...
Loading weights: 100%|█| 290/290 [00:00<00:00, 1596.04it/s, Materializing param=
Model loaded in:     0.36s
LoRA Attached:       4,399,104 trainable params (0.88% of 498,431,872)

Executing 1 Training Step (4 micro-batches of 8 samples = 32 samples, checkpointing=True) ...
{'loss': '3.947', 'grad_norm': '12.69', 'learning_rate': '0.0002', 'epoch': '1'}
{'train_runtime': '3.411', 'train_samples_per_second': '9.382', 'train_steps_per_second': '0.293', 'train_loss': '3.947', 'epoch': '1'}
100%|█████████████████████████████████████████████| 1/1 [00:03<00:00,  3.41s/it]
Step Completed in:   3.72s
Training Loss:       3.9466
Peak GPU VRAM:       1636.2 MB (~1.60 GB)
Smoke Test Results:  Saved successfully to outputs/smoke_test/smoke_test_results.json
=================================================================
GPU SMOKE TEST PASSED SUCCESSFULLY!
=================================================================

### Step 4: Generate Full 52k Importance Scoring Cache
Computes tri-component scores (Diversity + Complexity + Response Length) on GPU (~45–60s) and caches to `data/scored_alpaca.json`.

In [10]:
import json
from pathlib import Path
from src.utils import load_config, set_seed
from src.data_utils import load_alpaca_dataset
from src.scoring import score_dataset

config = load_config("configs/base_config.yaml")
set_seed(config["seed"])

cache_path = Path("/kaggle/working/efficient-llm-finetuning/data/scored_alpaca.json")
if not cache_path.exists():
    print("Loading Alpaca dataset for scoring...")
    train_ds, _ = load_alpaca_dataset(config)
    train_examples = [dict(ex) for ex in train_ds]
    print(f"Computing importance scores for {len(train_examples)} examples on GPU...")
    scored = score_dataset(train_examples, config)
    cache_path.parent.mkdir(parents=True, exist_ok=True)
    with open(cache_path, "w") as f:
        json.dump(scored, f)
    print(f"Scores successfully cached to {cache_path} ({len(scored)} items).")
else:
    print(f"Cached scores already exist at {cache_path}.")

Cached scores already exist at /kaggle/working/efficient-llm-finetuning/data/scored_alpaca.json.

### Step 5: Execute Primary Experiment Suite (E1 – E5)
Runs all experiments sequentially with fixed seed `42` and identical LoRA configuration.

In [22]:
!python src/train_baseline.py --config configs/exp1_baseline.yaml

2026-08-20 22:19:21 | INFO     | train | === Experiment E1: full_baseline | seed=42 ===
2026-08-20 22:19:21 | INFO     | train | Config: configs/exp1_baseline.yaml
2026-08-20 22:19:21 | INFO     | train | GPU free at experiment start: 12.83 GB / 14.56 GB
2026-08-20 22:19:22 | INFO     | data_utils | Loading dataset: tatsu-lab/alpaca
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-08-20 22:19:23 | INFO     | data_utils | Train: 49401, Eval: 2601
2026-08-20 22:19:26 | INFO     | train | Loading cached scores from data/scored_alpaca.json
2026-08-20 22:19:27 | INFO     | select_and_order | Selection: method=full, fraction=1.0, n_total=49401
2026-08-20 22:19:27 | INFO     | select_and_order | Selected 49401 / 49401 examples (100.0%)
2026-08-20 22:19:27 | INFO     | train | Training on 49401 examples
Skipping import of cpp extensions due to incompatible torch version. Please upgrade to torch >= 2.11.0 (found 2.10.0+cu128).
2026-08-20 22:19:33 | INFO     | train | Loading model: Qwen/Qwen2.5-0.5B-Instruct
Loading weights: 100%|█| 290/290 [00:00<00:00, 1471.48it/s, Materializing param=
trainable params: 4,399,104 || all params: 498,431,872 || trainable%: 0.8826
2026-08-20 22:19:35 | INFO     | train | Trainable params: 4,399,104 (0.88% of 498,431,872)
Tokenising: 100%|████████████████| 49401/49401 [00:07<00:00, 6219.44 examples/s]
Tokenising: 100%|██████████████████| 2601/2601 [00:00<00:00, 5954.26 examples/s]
2026-08-20 22:19:47 | INFO     | train | Training started ...
{'loss': '1.517', 'grad_norm': '0.6117', 'learning_rate': '0.0002', 'epoch': '0.03238'}
{'loss': '1.297', 'grad_norm': '0.5467', 'learning_rate': '0.0001994', 'epoch': '0.06477'}
{'loss': '1.237', 'grad_norm': '0.5303', 'learning_rate': '0.0001977', 'epoch': '0.09715'}
{'loss': '1.242', 'grad_norm': '0.5133', 'learning_rate': '0.000195', 'epoch': '0.1295'}
{'loss': '1.229', 'grad_norm': '0.4653', 'learning_rate': '0.0001911', 'epoch': '0.1619'}
{'loss': '1.213', 'grad_norm': '0.4532', 'learning_rate': '0.0001863', 'epoch': '0.1943'}
{'loss': '1.22', 'grad_norm': '0.4397', 'learning_rate': '0.0001806', 'epoch': '0.2267'}
{'loss': '1.251', 'grad_norm': '0.4398', 'learning_rate': '0.0001739', 'epoch': '0.2591'}
{'loss': '1.197', 'grad_norm': '0.4979', 'learning_rate': '0.0001665', 'epoch': '0.2915'}
{'loss': '1.21', 'grad_norm': '0.4433', 'learning_rate': '0.0001583', 'epoch': '0.3238'}
{'loss': '1.197', 'grad_norm': '0.4705', 'learning_rate': '0.0001495', 'epoch': '0.3562'}
{'loss': '1.206', 'grad_norm': '0.4422', 'learning_rate': '0.0001401', 'epoch': '0.3886'}
{'loss': '1.226', 'grad_norm': '0.4354', 'learning_rate': '0.0001303', 'epoch': '0.421'}
{'loss': '1.189', 'grad_norm': '0.5338', 'learning_rate': '0.0001201', 'epoch': '0.4534'}
{'loss': '1.208', 'grad_norm': '0.4228', 'learning_rate': '0.0001097', 'epoch': '0.4858'}
{'loss': '1.21', 'grad_norm': '0.4825', 'learning_rate': '9.927e-05', 'epoch': '0.5181'}
{'loss': '1.208', 'grad_norm': '0.4676', 'learning_rate': '8.88e-05', 'epoch': '0.5505'}
{'loss': '1.184', 'grad_norm': '0.4244', 'learning_rate': '7.845e-05', 'epoch': '0.5829'}
{'loss': '1.204', 'grad_norm': '0.4651', 'learning_rate': '6.834e-05', 'epoch': '0.6153'}
{'loss': '1.222', 'grad_norm': '0.5023', 'learning_rate': '5.858e-05', 'epoch': '0.6477'}
{'loss': '1.215', 'grad_norm': '0.4209', 'learning_rate': '4.927e-05', 'epoch': '0.6801'}
{'loss': '1.214', 'grad_norm': '0.4572', 'learning_rate': '4.053e-05', 'epoch': '0.7124'}
{'loss': '1.224', 'grad_norm': '0.4923', 'learning_rate': '3.243e-05', 'epoch': '0.7448'}
{'loss': '1.194', 'grad_norm': '0.4647', 'learning_rate': '2.508e-05', 'epoch': '0.7772'}
{'loss': '1.179', 'grad_norm': '0.4545', 'learning_rate': '1.856e-05', 'epoch': '0.8096'}
{'loss': '1.195', 'grad_norm': '0.453', 'learning_rate': '1.293e-05', 'epoch': '0.842'}
{'loss': '1.196', 'grad_norm': '0.414', 'learning_rate': '8.257e-06', 'epoch': '0.8744'}
{'loss': '1.207', 'grad_norm': '0.4629', 'learning_rate': '4.594e-06', 'epoch': '0.9067'}
{'loss': '1.198', 'grad_norm': '0.4324', 'learning_rate': '1.981e-06', 'epoch': '0.9391'}
{'loss': '1.187', 'grad_norm': '0.4086', 'learning_rate': '4.456e-07', 'epoch': '0.9715'}
100%|█████████████████████████████████████| 1544/1544 [1:04:09<00:00,  2.37s/it]
  0%|                                                   | 0/326 [00:00<?, ?it/s]
  1%|▎                                          | 2/326 [00:00<00:23, 14.07it/s]
  1%|▌                                          | 4/326 [00:00<00:48,  6.63it/s]
  2%|▋                                          | 5/326 [00:00<01:01,  5.24it/s]
  2%|▊                                          | 6/326 [00:01<00:59,  5.42it/s]
  2%|▉                                          | 7/326 [00:01<01:00,  5.24it/s]
  2%|█                                          | 8/326 [00:01<00:59,  5.34it/s]
  3%|█▏                                         | 9/326 [00:01<00:55,  5.72it/s]
  3%|█▎                                        | 10/326 [00:01<00:56,  5.61it/s]
  3%|█▍                                        | 11/326 [00:01<00:49,  6.41it/s]
  4%|█▌                                        | 12/326 [00:01<00:46,  6.70it/s]
  4%|█▋                                        | 13/326 [00:02<00:44,  7.04it/s]
  4%|█▊                                        | 14/326 [00:02<00:45,  6.85it/s]
  5%|█▉                                        | 15/326 [00:02<00:48,  6.47it/s]
  5%|██                                        | 16/326 [00:02<00:51,  6.04it/s]
  5%|██▏                                       | 17/326 [00:02<00:54,  5.72it/s]
  6%|██▎                                       | 18/326 [00:03<01:03,  4.83it/s]
  6%|██▍                                       | 19/326 [00:03<01:11,  4.31it/s]
  6%|██▌                                       | 20/326 [00:03<01:05,  4.70it/s]
  6%|██▋                                       | 21/326 [00:03<00:58,  5.25it/s]
  7%|██▊                                       | 22/326 [00:03<00:52,  5.82it/s]
  7%|██▉                                       | 23/326 [00:04<00:53,  5.65it/s]
  7%|███                                       | 24/326 [00:04<00:54,  5.53it/s]
  8%|███▏                                      | 25/326 [00:04<00:50,  5.91it/s]
  8%|███▎                                      | 26/326 [00:04<00:49,  6.08it/s]
  8%|███▍                                      | 27/326 [00:04<00:53,  5.61it/s]
  9%|███▌                                      | 28/326 [00:04<00:56,  5.26it/s]
  9%|███▋                                      | 29/326 [00:05<00:52,  5.62it/s]
  9%|███▊                                      | 30/326 [00:05<00:50,  5.86it/s]
 10%|███▉                                      | 31/326 [00:05<00:50,  5.80it/s]
 10%|████                                      | 32/326 [00:05<00:50,  5.85it/s]
 10%|████▎                                     | 33/326 [00:05<00:50,  5.83it/s]
 10%|████▍                                     | 34/326 [00:05<00:50,  5.76it/s]
 11%|████▌                                     | 35/326 [00:06<00:52,  5.59it/s]
 11%|████▋                                     | 36/326 [00:06<00:54,  5.30it/s]
 11%|████▊                                     | 37/326 [00:06<00:58,  4.94it/s]
 12%|████▉                                     | 38/326 [00:06<00:58,  4.94it/s]
 12%|█████                                     | 39/326 [00:06<00:58,  4.95it/s]
 12%|█████▏                                    | 40/326 [00:07<01:05,  4.36it/s]
 13%|█████▎                                    | 41/326 [00:07<01:11,  3.97it/s]
 13%|█████▍                                    | 42/326 [00:07<01:07,  4.21it/s]
 13%|█████▌                                    | 43/326 [00:07<01:02,  4.51it/s]
 13%|█████▋                                    | 44/326 [00:08<00:59,  4.72it/s]
 14%|█████▊                                    | 45/326 [00:08<00:57,  4.91it/s]
 14%|█████▉                                    | 46/326 [00:08<00:59,  4.68it/s]
 14%|██████                                    | 47/326 [00:08<01:03,  4.36it/s]
 15%|██████▏                                   | 48/326 [00:09<01:02,  4.45it/s]
 15%|██████▎                                   | 49/326 [00:09<00:58,  4.71it/s]
 15%|██████▍                                   | 50/326 [00:09<00:55,  4.96it/s]
 16%|██████▌                                   | 51/326 [00:09<00:58,  4.74it/s]
 16%|██████▋                                   | 52/326 [00:09<00:53,  5.12it/s]
 16%|██████▊                                   | 53/326 [00:09<00:50,  5.38it/s]
 17%|██████▉                                   | 54/326 [00:10<00:48,  5.62it/s]
 17%|███████                                   | 55/326 [00:10<00:43,  6.21it/s]
 17%|███████▏                                  | 56/326 [00:10<00:41,  6.54it/s]
 17%|███████▎                                  | 57/326 [00:10<00:42,  6.36it/s]
 18%|███████▍                                  | 58/326 [00:10<00:45,  5.95it/s]
 18%|███████▌                                  | 59/326 [00:10<00:47,  5.66it/s]
 18%|███████▋                                  | 60/326 [00:11<00:48,  5.44it/s]
 19%|███████▊                                  | 61/326 [00:11<00:50,  5.22it/s]
 19%|███████▉                                  | 62/326 [00:11<00:56,  4.70it/s]
 19%|████████                                  | 63/326 [00:11<01:01,  4.29it/s]
 20%|████████▏                                 | 64/326 [00:12<00:55,  4.76it/s]
 20%|████████▎                                 | 65/326 [00:12<00:52,  5.00it/s]
 20%|████████▌                                 | 66/326 [00:12<00:48,  5.31it/s]
 21%|████████▋                                 | 67/326 [00:12<00:43,  5.95it/s]
 21%|████████▊                                 | 68/326 [00:12<00:43,  5.98it/s]
 21%|████████▉                                 | 69/326 [00:12<00:46,  5.55it/s]
 21%|█████████                                 | 70/326 [00:13<00:51,  4.94it/s]
 22%|█████████▏                                | 71/326 [00:13<00:51,  4.91it/s]
 22%|█████████▎                                | 72/326 [00:13<00:51,  4.90it/s]
 22%|█████████▍                                | 73/326 [00:13<00:51,  4.90it/s]
 23%|█████████▌                                | 74/326 [00:13<00:49,  5.09it/s]
 23%|█████████▋                                | 75/326 [00:14<00:48,  5.19it/s]
 23%|█████████▊                                | 76/326 [00:14<00:50,  4.96it/s]
 24%|█████████▉                                | 77/326 [00:14<00:52,  4.71it/s]
 24%|██████████                                | 78/326 [00:14<00:50,  4.86it/s]
 24%|██████████▏                               | 79/326 [00:14<00:49,  4.97it/s]
 25%|██████████▎                               | 80/326 [00:15<00:48,  5.09it/s]
 25%|██████████▍                               | 81/326 [00:15<00:47,  5.14it/s]
 25%|██████████▌                               | 82/326 [00:15<00:45,  5.31it/s]
 25%|██████████▋                               | 83/326 [00:15<00:45,  5.39it/s]
 26%|██████████▊                               | 84/326 [00:15<00:45,  5.35it/s]
 26%|██████████▉                               | 85/326 [00:16<00:44,  5.36it/s]
 26%|███████████                               | 86/326 [00:16<00:44,  5.41it/s]
 27%|███████████▏                              | 87/326 [00:16<00:39,  6.04it/s]
 27%|███████████▎                              | 88/326 [00:16<00:37,  6.36it/s]
 27%|███████████▍                              | 89/326 [00:16<00:41,  5.78it/s]
 28%|███████████▌                              | 90/326 [00:16<00:43,  5.42it/s]
 28%|███████████▋                              | 91/326 [00:17<00:41,  5.60it/s]
 28%|███████████▊                              | 92/326 [00:17<00:44,  5.28it/s]
 29%|███████████▉                              | 93/326 [00:17<00:47,  4.89it/s]
 29%|████████████                              | 94/326 [00:17<00:46,  5.02it/s]
 29%|████████████▏                             | 95/326 [00:17<00:45,  5.04it/s]
 29%|████████████▎                             | 96/326 [00:18<00:44,  5.22it/s]
 30%|████████████▍                             | 97/326 [00:18<00:42,  5.45it/s]
 30%|████████████▋                             | 98/326 [00:18<00:40,  5.66it/s]
 30%|████████████▊                             | 99/326 [00:18<00:41,  5.49it/s]
 31%|████████████▌                            | 100/326 [00:18<00:42,  5.37it/s]
 31%|████████████▋                            | 101/326 [00:18<00:42,  5.29it/s]
 31%|████████████▊                            | 102/326 [00:19<00:43,  5.19it/s]
 32%|████████████▉                            | 103/326 [00:19<00:41,  5.36it/s]
 32%|█████████████                            | 104/326 [00:19<00:43,  5.14it/s]
 32%|█████████████▏                           | 105/326 [00:19<00:44,  4.96it/s]
 33%|█████████████▎                           | 106/326 [00:19<00:40,  5.49it/s]
 33%|█████████████▍                           | 107/326 [00:20<00:38,  5.63it/s]
 33%|█████████████▌                           | 108/326 [00:20<00:41,  5.27it/s]
 33%|█████████████▋                           | 109/326 [00:20<00:44,  4.82it/s]
 34%|█████████████▊                           | 110/326 [00:20<00:43,  4.91it/s]
 34%|█████████████▉                           | 111/326 [00:20<00:43,  4.95it/s]
 34%|██████████████                           | 112/326 [00:21<00:42,  5.06it/s]
 35%|██████████████▏                          | 113/326 [00:21<00:42,  4.99it/s]
 35%|██████████████▎                          | 114/326 [00:21<00:46,  4.58it/s]
 35%|██████████████▍                          | 115/326 [00:21<00:46,  4.49it/s]
 36%|██████████████▌                          | 116/326 [00:21<00:42,  4.98it/s]
 36%|██████████████▋                          | 117/326 [00:22<00:44,  4.73it/s]
 36%|██████████████▊                          | 118/326 [00:22<00:46,  4.46it/s]
 37%|██████████████▉                          | 119/326 [00:22<00:42,  4.91it/s]
 37%|███████████████                          | 120/326 [00:22<00:39,  5.19it/s]
 37%|███████████████▏                         | 121/326 [00:22<00:39,  5.22it/s]
 37%|███████████████▎                         | 122/326 [00:23<00:40,  4.98it/s]
 38%|███████████████▍                         | 123/326 [00:23<00:41,  4.91it/s]
 38%|███████████████▌                         | 124/326 [00:23<00:37,  5.44it/s]
 38%|███████████████▋                         | 125/326 [00:23<00:35,  5.65it/s]
 39%|███████████████▊                         | 126/326 [00:23<00:35,  5.65it/s]
 39%|███████████████▉                         | 127/326 [00:24<00:34,  5.72it/s]
 39%|████████████████                         | 128/326 [00:24<00:34,  5.67it/s]
 40%|████████████████▏                        | 129/326 [00:24<00:35,  5.52it/s]
 40%|████████████████▎                        | 130/326 [00:24<00:35,  5.56it/s]
 40%|████████████████▍                        | 131/326 [00:24<00:39,  4.88it/s]
 40%|████████████████▌                        | 132/326 [00:25<00:46,  4.20it/s]
 41%|████████████████▋                        | 133/326 [00:25<00:49,  3.88it/s]
 41%|████████████████▊                        | 134/326 [00:25<00:46,  4.17it/s]
 41%|████████████████▉                        | 135/326 [00:25<00:42,  4.49it/s]
 42%|█████████████████                        | 136/326 [00:26<00:38,  4.94it/s]
 42%|█████████████████▏                       | 137/326 [00:26<00:34,  5.50it/s]
 42%|█████████████████▎                       | 138/326 [00:26<00:33,  5.64it/s]
 43%|█████████████████▍                       | 139/326 [00:26<00:30,  6.10it/s]
 43%|█████████████████▌                       | 140/326 [00:26<00:28,  6.49it/s]
 43%|█████████████████▋                       | 141/326 [00:26<00:27,  6.65it/s]
 44%|█████████████████▊                       | 142/326 [00:26<00:28,  6.43it/s]
 44%|█████████████████▉                       | 143/326 [00:27<00:29,  6.16it/s]
 44%|██████████████████                       | 144/326 [00:27<00:30,  5.93it/s]
 44%|██████████████████▏                      | 145/326 [00:27<00:32,  5.56it/s]
 45%|██████████████████▎                      | 146/326 [00:27<00:35,  5.01it/s]
 45%|██████████████████▍                      | 147/326 [00:27<00:38,  4.69it/s]
 45%|██████████████████▌                      | 148/326 [00:28<00:37,  4.75it/s]
 46%|██████████████████▋                      | 149/326 [00:28<00:35,  5.04it/s]
 46%|██████████████████▊                      | 150/326 [00:28<00:31,  5.58it/s]
 46%|██████████████████▉                      | 151/326 [00:28<00:33,  5.20it/s]
 47%|███████████████████                      | 152/326 [00:28<00:37,  4.60it/s]
 47%|███████████████████▏                     | 153/326 [00:29<00:36,  4.71it/s]
 47%|███████████████████▎                     | 154/326 [00:29<00:33,  5.12it/s]
 48%|███████████████████▍                     | 155/326 [00:29<00:33,  5.11it/s]
 48%|███████████████████▌                     | 156/326 [00:29<00:32,  5.17it/s]
 48%|███████████████████▋                     | 157/326 [00:29<00:31,  5.34it/s]
 48%|███████████████████▊                     | 158/326 [00:30<00:32,  5.24it/s]
 49%|███████████████████▉                     | 159/326 [00:30<00:33,  5.05it/s]
 49%|████████████████████                     | 160/326 [00:30<00:36,  4.53it/s]
 49%|████████████████████▏                    | 161/326 [00:30<00:41,  4.02it/s]
 50%|████████████████████▎                    | 162/326 [00:31<00:39,  4.11it/s]
 50%|████████████████████▌                    | 163/326 [00:31<00:37,  4.34it/s]
 50%|████████████████████▋                    | 164/326 [00:31<00:35,  4.52it/s]
 51%|████████████████████▊                    | 165/326 [00:31<00:34,  4.63it/s]
 51%|████████████████████▉                    | 166/326 [00:31<00:32,  4.91it/s]
 51%|█████████████████████                    | 167/326 [00:32<00:28,  5.49it/s]
 52%|█████████████████████▏                   | 168/326 [00:32<00:28,  5.59it/s]
 52%|█████████████████████▎                   | 169/326 [00:32<00:28,  5.53it/s]
 52%|█████████████████████▍                   | 170/326 [00:32<00:27,  5.68it/s]
 52%|█████████████████████▌                   | 171/326 [00:32<00:25,  5.99it/s]
 53%|█████████████████████▋                   | 172/326 [00:32<00:27,  5.67it/s]
 53%|█████████████████████▊                   | 173/326 [00:33<00:28,  5.35it/s]
 53%|█████████████████████▉                   | 174/326 [00:33<00:28,  5.26it/s]
 54%|██████████████████████                   | 175/326 [00:33<00:28,  5.36it/s]
 54%|██████████████████████▏                  | 176/326 [00:33<00:27,  5.50it/s]
 54%|██████████████████████▎                  | 177/326 [00:33<00:30,  4.95it/s]
 55%|██████████████████████▍                  | 178/326 [00:34<00:34,  4.30it/s]
 55%|██████████████████████▌                  | 179/326 [00:34<00:32,  4.53it/s]
 55%|██████████████████████▋                  | 180/326 [00:34<00:32,  4.46it/s]
 56%|██████████████████████▊                  | 181/326 [00:34<00:34,  4.15it/s]
 56%|██████████████████████▉                  | 182/326 [00:35<00:32,  4.38it/s]
 56%|███████████████████████                  | 183/326 [00:35<00:32,  4.46it/s]
 56%|███████████████████████▏                 | 184/326 [00:35<00:28,  4.90it/s]
 57%|███████████████████████▎                 | 185/326 [00:35<00:27,  5.20it/s]
 57%|███████████████████████▍                 | 186/326 [00:35<00:25,  5.59it/s]
 57%|███████████████████████▌                 | 187/326 [00:35<00:24,  5.67it/s]
 58%|███████████████████████▋                 | 188/326 [00:36<00:25,  5.38it/s]
 58%|███████████████████████▊                 | 189/326 [00:36<00:26,  5.26it/s]
 58%|███████████████████████▉                 | 190/326 [00:36<00:25,  5.31it/s]
 59%|████████████████████████                 | 191/326 [00:36<00:26,  5.15it/s]
 59%|████████████████████████▏                | 192/326 [00:36<00:26,  5.04it/s]
 59%|████████████████████████▎                | 193/326 [00:37<00:26,  4.98it/s]
 60%|████████████████████████▍                | 194/326 [00:37<00:26,  4.93it/s]

In [28]:
!cat /kaggle/working/efficient-llm-finetuning/efficient-llm-finetuning/outputs/E1_full_baseline/results.json

{
  "experiment_id": "E1",
  "experiment_name": "full_baseline",
  "config_path": "configs/exp1_baseline.yaml",
  "seed": 42,
  "n_train_examples": 49401,
  "n_eval_examples": 2601,
  "data_fraction": 1.0,
  "selection_method": "full",
  "ordering": "random",
  "wall_clock_seconds": 3913.36,
  "wall_clock_minutes": 65.22,
  "peak_gpu_memory_mb": 6887.6,
  "system_ram": {
    "used_mb": 3802.7,
    "total_mb": 32100.1,
    "percent": 13.4
  },
  "trainable_params": 4399104,
  "total_params": 498431872,
  "trainable_pct": 0.8826,
  "eval_loss": 1.1844764947891235,
  "eval_runtime": 63.1181,
  "eval_samples_per_second": 41.208,
  "eval_steps_per_second": 5.165,
  "epoch": 1.0,
  "train_loss": 1.2218394773611752
}

In [11]:
# E2 — Random 50% (random order, 3 epochs)
!python src/train_baseline.py --config configs/exp2_random50.yaml

2026-08-21 00:04:45 | INFO     | train | === Experiment E2: random50_random_order | seed=42 ===
2026-08-21 00:04:45 | INFO     | train | Config: configs/exp2_random50.yaml
2026-08-21 00:04:45 | INFO     | train | GPU free at experiment start: 14.36 GB / 14.56 GB
2026-08-21 00:04:46 | INFO     | data_utils | Loading dataset: tatsu-lab/alpaca
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-08-21 00:04:46 | INFO     | data_utils | Train: 49401, Eval: 2601
2026-08-21 00:04:50 | INFO     | train | Computing importance scores (this runs once and is cached) ...
2026-08-21 00:04:50 | INFO     | scoring | Scoring 49401 examples (a=0.333, b=0.333, g=0.334)
Skipping import of cpp extensions due to incompatible torch version. Please upgrade to torch >= 2.11.0 (found 2.10.0+cu128).
2026-08-21 00:04:58 | INFO     | scoring | Computing embeddings with all-MiniLM-L6-v2 ...
Loading weights: 100%|█| 103/103 [00:00<00:00, 1553.04it/s, Materializing param=
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Batches: 100%|████████████████████████████████| 193/193 [00:16<00:00, 11.64it/s]
2026-08-21 00:05:16 | INFO     | scoring | Importance score stats — mean: 0.6328, std: 0.0699, min: 0.3100, max: 0.9029
2026-08-21 00:05:16 | INFO     | train | Scores cached to data/scored_alpaca.json
2026-08-21 00:05:16 | INFO     | select_and_order | Selection: method=random, fraction=0.5, n_total=49401
2026-08-21 00:05:16 | INFO     | select_and_order | Selected 24700 / 49401 examples (50.0%)
2026-08-21 00:05:16 | INFO     | train | Training on 24700 examples
2026-08-21 00:05:16 | INFO     | train | Loading model: Qwen/Qwen2.5-0.5B-Instruct
Loading weights: 100%|█| 290/290 [00:00<00:00, 1688.91it/s, Materializing param=
trainable params: 4,399,104 || all params: 498,431,872 || trainable%: 0.8826
2026-08-21 00:05:19 | INFO     | train | Trainable params: 4,399,104 (0.88% of 498,431,872)
Tokenising: 100%|████████████████| 24700/24700 [00:04<00:00, 5921.03 examples/s]
Tokenising: 100%|██████████████████| 2601/2601 [00:00<00:00, 5897.88 examples/s]
2026-08-21 00:05:27 | INFO     | train | Training started ...
{'loss': '1.467', 'grad_norm': '0.5752', 'learning_rate': '0.0001994', 'epoch': '0.06477'}
{'loss': '1.242', 'grad_norm': '0.7092', 'learning_rate': '0.0001951', 'epoch': '0.1295'}
{'loss': '1.244', 'grad_norm': '0.4869', 'learning_rate': '0.0001865', 'epoch': '0.1943'}
{'loss': '1.237', 'grad_norm': '0.4809', 'learning_rate': '0.0001742', 'epoch': '0.2591'}
{'loss': '1.227', 'grad_norm': '0.4607', 'learning_rate': '0.0001586', 'epoch': '0.3238'}
{'loss': '1.207', 'grad_norm': '0.4543', 'learning_rate': '0.0001404', 'epoch': '0.3886'}
{'loss': '1.238', 'grad_norm': '0.4855', 'learning_rate': '0.0001204', 'epoch': '0.4534'}
{'loss': '1.209', 'grad_norm': '0.4616', 'learning_rate': '9.958e-05', 'epoch': '0.5181'}
{'loss': '1.21', 'grad_norm': '0.4379', 'learning_rate': '7.874e-05', 'epoch': '0.5829'}
{'loss': '1.226', 'grad_norm': '0.4352', 'learning_rate': '5.884e-05', 'epoch': '0.6477'}
{'loss': '1.202', 'grad_norm': '0.4492', 'learning_rate': '4.075e-05', 'epoch': '0.7124'}
{'loss': '1.214', 'grad_norm': '0.482', 'learning_rate': '2.526e-05', 'epoch': '0.7772'}
{'loss': '1.206', 'grad_norm': '0.4586', 'learning_rate': '1.305e-05', 'epoch': '0.842'}
{'loss': '1.215', 'grad_norm': '0.4823', 'learning_rate': '4.663e-06', 'epoch': '0.9067'}
{'loss': '1.22', 'grad_norm': '0.4463', 'learning_rate': '4.662e-07', 'epoch': '0.9715'}
100%|█████████████████████████████████████████| 772/772 [32:11<00:00,  2.15s/it]
  0%|                                                   | 0/326 [00:00<?, ?it/s]
  1%|▎                                          | 2/326 [00:00<00:23, 14.02it/s]
  1%|▌                                          | 4/326 [00:00<00:48,  6.64it/s]
  2%|▋                                          | 5/326 [00:00<01:00,  5.26it/s]
  2%|▊                                          | 6/326 [00:01<00:59,  5.40it/s]
  2%|▉                                          | 7/326 [00:01<01:01,  5.22it/s]
  2%|█                                          | 8/326 [00:01<00:59,  5.34it/s]
  3%|█▏                                         | 9/326 [00:01<00:55,  5.71it/s]
  3%|█▎                                        | 10/326 [00:01<00:58,  5.44it/s]
  3%|█▍                                        | 11/326 [00:01<00:51,  6.14it/s]
  4%|█▌                                        | 12/326 [00:01<00:46,  6.76it/s]
  4%|█▋                                        | 13/326 [00:02<00:44,  7.09it/s]
  4%|█▊                                        | 14/326 [00:02<00:45,  6.86it/s]
  5%|█▉                                        | 15/326 [00:02<00:47,  6.50it/s]
  5%|██                                        | 16/326 [00:02<00:51,  6.06it/s]
  5%|██▏                                       | 17/326 [00:02<00:53,  5.74it/s]
  6%|██▎                                       | 18/326 [00:03<01:03,  4.86it/s]
  6%|██▍                                       | 19/326 [00:03<01:11,  4.32it/s]
  6%|██▌                                       | 20/326 [00:03<01:04,  4.73it/s]
  6%|██▋                                       | 21/326 [00:03<00:58,  5.24it/s]
  7%|██▊                                       | 22/326 [00:03<00:52,  5.79it/s]
  7%|██▉                                       | 23/326 [00:04<00:53,  5.62it/s]
  7%|███                                       | 24/326 [00:04<00:54,  5.56it/s]
  8%|███▏                                      | 25/326 [00:04<00:51,  5.88it/s]
  8%|███▎                                      | 26/326 [00:04<00:49,  6.06it/s]
  8%|███▍                                      | 27/326 [00:04<00:53,  5.61it/s]
  9%|███▌                                      | 28/326 [00:04<00:56,  5.26it/s]
  9%|███▋                                      | 29/326 [00:05<00:52,  5.63it/s]
  9%|███▊                                      | 30/326 [00:05<00:50,  5.86it/s]
 10%|███▉                                      | 31/326 [00:05<00:50,  5.80it/s]
 10%|████                                      | 32/326 [00:05<00:50,  5.83it/s]
 10%|████▎                                     | 33/326 [00:05<00:50,  5.82it/s]
 10%|████▍                                     | 34/326 [00:05<00:50,  5.74it/s]
 11%|████▌                                     | 35/326 [00:06<00:52,  5.59it/s]
 11%|████▋                                     | 36/326 [00:06<00:54,  5.30it/s]
 11%|████▊                                     | 37/326 [00:06<00:58,  4.93it/s]
 12%|████▉                                     | 38/326 [00:06<00:58,  4.93it/s]
 12%|█████                                     | 39/326 [00:06<00:57,  4.95it/s]
 12%|█████▏                                    | 40/326 [00:07<01:05,  4.36it/s]
 13%|█████▎                                    | 41/326 [00:07<01:11,  3.98it/s]
 13%|█████▍                                    | 42/326 [00:07<01:07,  4.22it/s]
 13%|█████▌                                    | 43/326 [00:07<01:02,  4.54it/s]
 13%|█████▋                                    | 44/326 [00:08<00:59,  4.75it/s]
 14%|█████▊                                    | 45/326 [00:08<00:57,  4.93it/s]
 14%|█████▉                                    | 46/326 [00:08<00:59,  4.69it/s]
 14%|██████                                    | 47/326 [00:08<01:03,  4.39it/s]
 15%|██████▏                                   | 48/326 [00:09<01:02,  4.47it/s]
 15%|██████▎                                   | 49/326 [00:09<00:58,  4.72it/s]
 15%|██████▍                                   | 50/326 [00:09<00:55,  4.97it/s]
 16%|██████▌                                   | 51/326 [00:09<00:57,  4.75it/s]
 16%|██████▋                                   | 52/326 [00:09<00:53,  5.12it/s]
 16%|██████▊                                   | 53/326 [00:09<00:50,  5.40it/s]
 17%|██████▉                                   | 54/326 [00:10<00:48,  5.62it/s]
 17%|███████                                   | 55/326 [00:10<00:43,  6.25it/s]
 17%|███████▏                                  | 56/326 [00:10<00:41,  6.55it/s]
 17%|███████▎                                  | 57/326 [00:10<00:42,  6.37it/s]
 18%|███████▍                                  | 58/326 [00:10<00:44,  5.96it/s]
 18%|███████▌                                  | 59/326 [00:10<00:47,  5.68it/s]
 18%|███████▋                                  | 60/326 [00:11<00:48,  5.46it/s]
 19%|███████▊                                  | 61/326 [00:11<00:50,  5.24it/s]
 19%|███████▉                                  | 62/326 [00:11<00:55,  4.73it/s]
 19%|████████                                  | 63/326 [00:11<01:03,  4.17it/s]
 20%|████████▏                                 | 64/326 [00:12<00:54,  4.80it/s]
 20%|████████▎                                 | 65/326 [00:12<00:51,  5.02it/s]
 20%|████████▌                                 | 66/326 [00:12<00:48,  5.31it/s]
 21%|████████▋                                 | 67/326 [00:12<00:43,  6.01it/s]
 21%|████████▊                                 | 68/326 [00:12<00:42,  6.04it/s]
 21%|████████▉                                 | 69/326 [00:12<00:45,  5.62it/s]
 21%|█████████                                 | 70/326 [00:13<00:51,  4.98it/s]
 22%|█████████▏                                | 71/326 [00:13<00:51,  4.96it/s]
 22%|█████████▎                                | 72/326 [00:13<00:51,  4.95it/s]
 22%|█████████▍                                | 73/326 [00:13<00:51,  4.94it/s]
 23%|█████████▌                                | 74/326 [00:13<00:49,  5.13it/s]
 23%|█████████▋                                | 75/326 [00:14<00:47,  5.24it/s]
 23%|█████████▊                                | 76/326 [00:14<00:50,  4.99it/s]
 24%|█████████▉                                | 77/326 [00:14<00:52,  4.74it/s]
 24%|██████████                                | 78/326 [00:14<00:50,  4.88it/s]
 24%|██████████▏                               | 79/326 [00:14<00:49,  4.98it/s]
 25%|██████████▎                               | 80/326 [00:15<00:48,  5.11it/s]
 25%|██████████▍                               | 81/326 [00:15<00:47,  5.16it/s]
 25%|██████████▌                               | 82/326 [00:15<00:45,  5.32it/s]
 25%|██████████▋                               | 83/326 [00:15<00:45,  5.40it/s]
 26%|██████████▊                               | 84/326 [00:15<00:45,  5.37it/s]
 26%|██████████▉                               | 85/326 [00:16<00:44,  5.40it/s]
 26%|███████████                               | 86/326 [00:16<00:43,  5.48it/s]
 27%|███████████▏                              | 87/326 [00:16<00:39,  6.05it/s]
 27%|███████████▎                              | 88/326 [00:16<00:37,  6.41it/s]
 27%|███████████▍                              | 89/326 [00:16<00:40,  5.82it/s]
 28%|███████████▌                              | 90/326 [00:16<00:43,  5.46it/s]
 28%|███████████▋                              | 91/326 [00:17<00:41,  5.64it/s]
 28%|███████████▊                              | 92/326 [00:17<00:44,  5.30it/s]
 29%|███████████▉                              | 93/326 [00:17<00:47,  4.90it/s]
 29%|████████████                              | 94/326 [00:17<00:46,  5.03it/s]
 29%|████████████▏                             | 95/326 [00:17<00:45,  5.05it/s]
 29%|████████████▎                             | 96/326 [00:18<00:44,  5.22it/s]
 30%|████████████▍                             | 97/326 [00:18<00:41,  5.45it/s]
 30%|████████████▋                             | 98/326 [00:18<00:40,  5.67it/s]
 30%|████████████▊                             | 99/326 [00:18<00:41,  5.49it/s]
 31%|████████████▌                            | 100/326 [00:18<00:41,  5.39it/s]
 31%|████████████▋                            | 101/326 [00:18<00:42,  5.31it/s]
 31%|████████████▊                            | 102/326 [00:19<00:43,  5.19it/s]
 32%|████████████▉                            | 103/326 [00:19<00:41,  5.36it/s]
 32%|█████████████                            | 104/326 [00:19<00:43,  5.12it/s]
 32%|█████████████▏                           | 105/326 [00:19<00:44,  4.94it/s]
 33%|█████████████▎                           | 106/326 [00:19<00:39,  5.50it/s]
 33%|█████████████▍                           | 107/326 [00:20<00:38,  5.63it/s]
 33%|█████████████▌                           | 108/326 [00:20<00:41,  5.28it/s]
 33%|█████████████▋                           | 109/326 [00:20<00:44,  4.85it/s]
 34%|█████████████▊                           | 110/326 [00:20<00:43,  4.93it/s]
 34%|█████████████▉                           | 111/326 [00:20<00:43,  4.97it/s]
 34%|██████████████                           | 112/326 [00:21<00:42,  5.08it/s]
 35%|██████████████▏                          | 113/326 [00:21<00:42,  5.01it/s]
 35%|██████████████▎                          | 114/326 [00:21<00:46,  4.60it/s]
 35%|██████████████▍                          | 115/326 [00:21<00:47,  4.45it/s]
 36%|██████████████▌                          | 116/326 [00:21<00:42,  4.99it/s]
 36%|██████████████▋                          | 117/326 [00:22<00:43,  4.75it/s]
 36%|██████████████▊                          | 118/326 [00:22<00:46,  4.49it/s]
 37%|██████████████▉                          | 119/326 [00:22<00:41,  4.96it/s]
 37%|███████████████                          | 120/326 [00:22<00:39,  5.20it/s]
 37%|███████████████▏                         | 121/326 [00:22<00:39,  5.25it/s]
 37%|███████████████▎                         | 122/326 [00:23<00:40,  4.99it/s]
 38%|███████████████▍                         | 123/326 [00:23<00:41,  4.92it/s]
 38%|███████████████▌                         | 124/326 [00:23<00:36,  5.48it/s]
 38%|███████████████▋                         | 125/326 [00:23<00:35,  5.69it/s]
 39%|███████████████▊                         | 126/326 [00:23<00:35,  5.68it/s]
 39%|███████████████▉                         | 127/326 [00:24<00:34,  5.75it/s]
 39%|████████████████                         | 128/326 [00:24<00:34,  5.72it/s]
 40%|████████████████▏                        | 129/326 [00:24<00:34,  5.65it/s]
 40%|████████████████▎                        | 130/326 [00:24<00:35,  5.55it/s]
 40%|████████████████▍                        | 131/326 [00:24<00:39,  4.89it/s]
 40%|████████████████▌                        | 132/326 [00:25<00:46,  4.22it/s]
 41%|████████████████▋                        | 133/326 [00:25<00:49,  3.90it/s]
 41%|████████████████▊                        | 134/326 [00:25<00:45,  4.19it/s]
 41%|████████████████▉                        | 135/326 [00:25<00:42,  4.51it/s]
 42%|█████████████████                        | 136/326 [00:25<00:38,  4.98it/s]
 42%|█████████████████▏                       | 137/326 [00:26<00:34,  5.55it/s]
 42%|█████████████████▎                       | 138/326 [00:26<00:33,  5.69it/s]
 43%|█████████████████▍                       | 139/326 [00:26<00:30,  6.14it/s]
 43%|█████████████████▌                       | 140/326 [00:26<00:28,  6.52it/s]
 43%|█████████████████▋                       | 141/326 [00:26<00:27,  6.70it/s]
 44%|█████████████████▊                       | 142/326 [00:26<00:28,  6.47it/s]
 44%|█████████████████▉                       | 143/326 [00:27<00:29,  6.22it/s]
 44%|██████████████████                       | 144/326 [00:27<00:30,  5.95it/s]
 44%|██████████████████▏                      | 145/326 [00:27<00:32,  5.60it/s]
 45%|██████████████████▎                      | 146/326 [00:27<00:35,  5.05it/s]
 45%|██████████████████▍                      | 147/326 [00:27<00:37,  4.73it/s]
 45%|██████████████████▌                      | 148/326 [00:28<00:37,  4.81it/s]
 46%|██████████████████▋                      | 149/326 [00:28<00:34,  5.10it/s]
 46%|██████████████████▊                      | 150/326 [00:28<00:31,  5.59it/s]
 46%|██████████████████▉                      | 151/326 [00:28<00:33,  5.23it/s]
 47%|███████████████████                      | 152/326 [00:28<00:37,  4.63it/s]
 47%|███████████████████▏                     | 153/326 [00:29<00:36,  4.75it/s]
 47%|███████████████████▎                     | 154/326 [00:29<00:33,  5.19it/s]
 48%|███████████████████▍                     | 155/326 [00:29<00:33,  5.18it/s]
 48%|███████████████████▌                     | 156/326 [00:29<00:32,  5.24it/s]
 48%|███████████████████▋                     | 157/326 [00:29<00:31,  5.39it/s]
 48%|███████████████████▊                     | 158/326 [00:29<00:31,  5.29it/s]
 49%|███████████████████▉                     | 159/326 [00:30<00:32,  5.09it/s]
 49%|████████████████████                     | 160/326 [00:30<00:36,  4.56it/s]
 49%|████████████████████▏                    | 161/326 [00:30<00:40,  4.05it/s]
 50%|████████████████████▎                    | 162/326 [00:31<00:39,  4.14it/s]
 50%|████████████████████▌                    | 163/326 [00:31<00:37,  4.36it/s]
 50%|████████████████████▋                    | 164/326 [00:31<00:35,  4.54it/s]
 51%|████████████████████▊                    | 165/326 [00:31<00:34,  4.63it/s]
 51%|████████████████████▉                    | 166/326 [00:31<00:32,  4.88it/s]
 51%|█████████████████████                    | 167/326 [00:31<00:28,  5.51it/s]
 52%|█████████████████████▏                   | 168/326 [00:32<00:28,  5.59it/s]
 52%|█████████████████████▎                   | 169/326 [00:32<00:28,  5.54it/s]
 52%|█████████████████████▍                   | 170/326 [00:32<00:27,  5.70it/s]
 52%|█████████████████████▌                   | 171/326 [00:32<00:25,  5.99it/s]
 53%|█████████████████████▋                   | 172/326 [00:32<00:27,  5.67it/s]
 53%|█████████████████████▊                   | 173/326 [00:33<00:28,  5.36it/s]
 53%|█████████████████████▉                   | 174/326 [00:33<00:28,  5.27it/s]
 54%|██████████████████████                   | 175/326 [00:33<00:28,  5.36it/s]
 54%|██████████████████████▏                  | 176/326 [00:33<00:27,  5.54it/s]
 54%|██████████████████████▎                  | 177/326 [00:33<00:30,  4.96it/s]
 55%|██████████████████████▍                  | 178/326 [00:34<00:34,  4.30it/s]
 55%|██████████████████████▌                  | 179/326 [00:34<00:31,  4.66it/s]
 55%|██████████████████████▋                  | 180/326 [00:34<00:32,  4.44it/s]
 56%|██████████████████████▊                  | 181/326 [00:34<00:35,  4.13it/s]
 56%|██████████████████████▉                  | 182/326 [00:35<00:32,  4.38it/s]
 56%|███████████████████████                  | 183/326 [00:35<00:32,  4.44it/s]
 56%|███████████████████████▏                 | 184/326 [00:35<00:29,  4.88it/s]
 57%|███████████████████████▎                 | 185/326 [00:35<00:26,  5.27it/s]
 57%|███████████████████████▍                 | 186/326 [00:35<00:25,  5.57it/s]
 57%|███████████████████████▌                 | 187/326 [00:35<00:24,  5.65it/s]
 58%|███████████████████████▋                 | 188/326 [00:36<00:25,  5.36it/s]
 58%|███████████████████████▊                 | 189/326 [00:36<00:26,  5.24it/s]
 58%|███████████████████████▉                 | 190/326 [00:36<00:25,  5.31it/s]
 59%|████████████████████████                 | 191/326 [00:36<00:26,  5.15it/s]
 59%|████████████████████████▏                | 192/326 [00:36<00:26,  5.06it/s]
 59%|████████████████████████▎                | 193/326 [00:37<00:26,  5.00it/s]
 60%|████████████████████████▍                | 194/326 [00:37<00:26,  4.96it/s]
 60%|████████████████████████▌                | 195/326 [00:37<00:26,  4.96it/s]
 60%|████████████████████████▋                | 196/326 [00:37<00:27,  4.77it/s]
 60%|████████████████████████▊                | 197/326 [00:37<00:29,  4.31it/s]
 61%|████████████████████████▉                | 198/326 [00:38<00:27,  4.72it/s]
 61%|█████████████████████████                | 199/326 [00:38<00:24,  5.16it/s]

In [12]:
!ls -lh outputs/E2_random50_random/results.json
!cat outputs/E2_random50_random/results.json

-rw-r--r-- 1 root root 726 Aug 21 00:39 outputs/E2_random50_random/results.json
{
  "experiment_id": "E2",
  "experiment_name": "random50_random_order",
  "config_path": "configs/exp2_random50.yaml",
  "seed": 42,
  "n_train_examples": 24700,
  "n_eval_examples": 2601,
  "data_fraction": 0.5,
  "selection_method": "random",
  "ordering": "random",
  "wall_clock_seconds": 1995.79,
  "wall_clock_minutes": 33.26,
  "peak_gpu_memory_mb": 6887.6,
  "system_ram": {
    "used_mb": 3163.6,
    "total_mb": 32100.1,
    "percent": 11.4
  },
  "trainable_params": 4399104,
  "total_params": 498431872,
  "trainable_pct": 0.8826,
  "eval_loss": 1.1957964897155762,
  "eval_runtime": 63.41,
  "eval_samples_per_second": 41.019,
  "eval_steps_per_second": 5.141,
  "epoch": 1.0,
  "train_loss": 1.236928045440832
}

In [25]:
!python src/train_baseline.py --config configs/exp3_adaptive50_random.yaml

2026-08-21 00:47:04 | INFO     | train | === Experiment E3: adaptive50_random_order | seed=42 ===
2026-08-21 00:47:04 | INFO     | train | Config: configs/exp3_adaptive50_random.yaml
2026-08-21 00:47:04 | INFO     | train | GPU free at experiment start: 14.36 GB / 14.56 GB
2026-08-21 00:47:05 | INFO     | data_utils | Loading dataset: tatsu-lab/alpaca
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-08-21 00:47:06 | INFO     | data_utils | Train: 49401, Eval: 2601
2026-08-21 00:47:09 | INFO     | train | Loading cached scores from data/scored_alpaca.json
2026-08-21 00:47:09 | INFO     | select_and_order | Selection: method=adaptive, fraction=0.5, n_total=49401
2026-08-21 00:47:09 | INFO     | select_and_order | Selected 24700 / 49401 examples (50.0%)
2026-08-21 00:47:09 | INFO     | train | Training on 24700 examples
Skipping import of cpp extensions due to incompatible torch version. Please upgrade to torch >= 2.11.0 (found 2.10.0+cu128).
2026-08-21 00:47:15 | INFO     | train | Loading model: Qwen/Qwen2.5-0.5B-Instruct
Loading weights: 100%|█| 290/290 [00:00<00:00, 1484.04it/s, Materializing param=
trainable params: 4,399,104 || all params: 498,431,872 || trainable%: 0.8826
2026-08-21 00:47:18 | INFO     | train | Trainable params: 4,399,104 (0.88% of 498,431,872)
Tokenising: 100%|████████████████| 24700/24700 [00:03<00:00, 6612.91 examples/s]
Tokenising: 100%|██████████████████| 2601/2601 [00:00<00:00, 6018.13 examples/s]
2026-08-21 00:47:26 | INFO     | train | Training started ...
{'loss': '1.384', 'grad_norm': '0.7428', 'learning_rate': '0.0001994', 'epoch': '0.06477'}
{'loss': '1.168', 'grad_norm': '0.4593', 'learning_rate': '0.0001951', 'epoch': '0.1295'}
{'loss': '1.165', 'grad_norm': '0.5318', 'learning_rate': '0.0001865', 'epoch': '0.1943'}
{'loss': '1.153', 'grad_norm': '0.4973', 'learning_rate': '0.0001742', 'epoch': '0.2591'}
{'loss': '1.137', 'grad_norm': '0.455', 'learning_rate': '0.0001586', 'epoch': '0.3238'}
{'loss': '1.14', 'grad_norm': '0.4557', 'learning_rate': '0.0001404', 'epoch': '0.3886'}
{'loss': '1.145', 'grad_norm': '0.4661', 'learning_rate': '0.0001204', 'epoch': '0.4534'}
{'loss': '1.146', 'grad_norm': '0.4547', 'learning_rate': '9.958e-05', 'epoch': '0.5181'}
{'loss': '1.124', 'grad_norm': '0.5085', 'learning_rate': '7.874e-05', 'epoch': '0.5829'}
{'loss': '1.145', 'grad_norm': '0.5131', 'learning_rate': '5.884e-05', 'epoch': '0.6477'}
{'loss': '1.119', 'grad_norm': '0.4853', 'learning_rate': '4.075e-05', 'epoch': '0.7124'}
{'loss': '1.122', 'grad_norm': '0.4864', 'learning_rate': '2.526e-05', 'epoch': '0.7772'}
{'loss': '1.125', 'grad_norm': '0.4355', 'learning_rate': '1.305e-05', 'epoch': '0.842'}
{'loss': '1.137', 'grad_norm': '0.4882', 'learning_rate': '4.663e-06', 'epoch': '0.9067'}
{'loss': '1.121', 'grad_norm': '0.4497', 'learning_rate': '4.662e-07', 'epoch': '0.9715'}
100%|█████████████████████████████████████████| 772/772 [27:18<00:00,  2.05s/it]
  0%|                                                   | 0/326 [00:00<?, ?it/s]
  1%|▎                                          | 2/326 [00:00<00:23, 13.78it/s]
  1%|▌                                          | 4/326 [00:00<00:48,  6.63it/s]
  2%|▋                                          | 5/326 [00:00<01:01,  5.25it/s]
  2%|▊                                          | 6/326 [00:01<00:59,  5.40it/s]
  2%|▉                                          | 7/326 [00:01<01:01,  5.21it/s]
  2%|█                                          | 8/326 [00:01<00:59,  5.34it/s]
  3%|█▏                                         | 9/326 [00:01<00:55,  5.71it/s]
  3%|█▎                                        | 10/326 [00:01<00:56,  5.62it/s]
  3%|█▍                                        | 11/326 [00:01<00:49,  6.38it/s]
  4%|█▌                                        | 12/326 [00:01<00:47,  6.68it/s]
  4%|█▋                                        | 13/326 [00:02<00:44,  6.99it/s]
  4%|█▊                                        | 14/326 [00:02<00:45,  6.85it/s]
  5%|█▉                                        | 15/326 [00:02<00:48,  6.44it/s]
  5%|██                                        | 16/326 [00:02<00:51,  6.04it/s]
  5%|██▏                                       | 17/326 [00:02<00:53,  5.74it/s]
  6%|██▎                                       | 18/326 [00:03<01:03,  4.85it/s]
  6%|██▍                                       | 19/326 [00:03<01:11,  4.29it/s]
  6%|██▌                                       | 20/326 [00:03<01:04,  4.71it/s]
  6%|██▋                                       | 21/326 [00:03<00:58,  5.19it/s]
  7%|██▊                                       | 22/326 [00:03<00:52,  5.78it/s]
  7%|██▉                                       | 23/326 [00:04<00:54,  5.61it/s]
  7%|███                                       | 24/326 [00:04<00:54,  5.50it/s]
  8%|███▏                                      | 25/326 [00:04<00:51,  5.87it/s]
  8%|███▎                                      | 26/326 [00:04<00:49,  6.06it/s]
  8%|███▍                                      | 27/326 [00:04<00:53,  5.60it/s]
  9%|███▌                                      | 28/326 [00:04<00:56,  5.24it/s]
  9%|███▋                                      | 29/326 [00:05<00:53,  5.59it/s]
  9%|███▊                                      | 30/326 [00:05<00:50,  5.85it/s]
 10%|███▉                                      | 31/326 [00:05<00:50,  5.79it/s]
 10%|████                                      | 32/326 [00:05<00:50,  5.83it/s]
 10%|████▎                                     | 33/326 [00:05<00:50,  5.82it/s]
 10%|████▍                                     | 34/326 [00:05<00:50,  5.74it/s]
 11%|████▌                                     | 35/326 [00:06<00:52,  5.59it/s]
 11%|████▋                                     | 36/326 [00:06<00:54,  5.31it/s]
 11%|████▊                                     | 37/326 [00:06<00:58,  4.92it/s]
 12%|████▉                                     | 38/326 [00:06<00:58,  4.92it/s]
 12%|█████                                     | 39/326 [00:06<00:58,  4.92it/s]
 12%|█████▏                                    | 40/326 [00:07<01:05,  4.35it/s]
 13%|█████▎                                    | 41/326 [00:07<01:11,  3.96it/s]
 13%|█████▍                                    | 42/326 [00:07<01:07,  4.19it/s]
 13%|█████▌                                    | 43/326 [00:07<01:02,  4.50it/s]
 13%|█████▋                                    | 44/326 [00:08<00:59,  4.72it/s]
 14%|█████▊                                    | 45/326 [00:08<00:57,  4.89it/s]
 14%|█████▉                                    | 46/326 [00:08<01:00,  4.66it/s]
 14%|██████                                    | 47/326 [00:08<01:03,  4.36it/s]
 15%|██████▏                                   | 48/326 [00:09<01:02,  4.44it/s]
 15%|██████▎                                   | 49/326 [00:09<00:59,  4.69it/s]
 15%|██████▍                                   | 50/326 [00:09<00:55,  4.95it/s]
 16%|██████▌                                   | 51/326 [00:09<00:58,  4.74it/s]
 16%|██████▋                                   | 52/326 [00:09<00:54,  5.06it/s]
 16%|██████▊                                   | 53/326 [00:09<00:50,  5.40it/s]
 17%|██████▉                                   | 54/326 [00:10<00:48,  5.60it/s]
 17%|███████                                   | 55/326 [00:10<00:43,  6.22it/s]
 17%|███████▏                                  | 56/326 [00:10<00:41,  6.55it/s]
 17%|███████▎                                  | 57/326 [00:10<00:42,  6.34it/s]
 18%|███████▍                                  | 58/326 [00:10<00:45,  5.93it/s]
 18%|███████▌                                  | 59/326 [00:10<00:47,  5.65it/s]
 18%|███████▋                                  | 60/326 [00:11<00:48,  5.43it/s]
 19%|███████▊                                  | 61/326 [00:11<00:50,  5.21it/s]
 19%|███████▉                                  | 62/326 [00:11<00:56,  4.68it/s]
 19%|████████                                  | 63/326 [00:11<01:01,  4.25it/s]
 20%|████████▏                                 | 64/326 [00:12<00:55,  4.74it/s]
 20%|████████▎                                 | 65/326 [00:12<00:52,  4.96it/s]
 20%|████████▌                                 | 66/326 [00:12<00:49,  5.26it/s]
 21%|████████▋                                 | 67/326 [00:12<00:43,  5.96it/s]
 21%|████████▊                                 | 68/326 [00:12<00:43,  6.00it/s]
 21%|████████▉                                 | 69/326 [00:12<00:46,  5.57it/s]
 21%|█████████                                 | 70/326 [00:13<00:51,  4.96it/s]
 22%|█████████▏                                | 71/326 [00:13<00:51,  4.95it/s]
 22%|█████████▎                                | 72/326 [00:13<00:51,  4.94it/s]
 22%|█████████▍                                | 73/326 [00:13<00:51,  4.92it/s]
 23%|█████████▌                                | 74/326 [00:13<00:49,  5.12it/s]
 23%|█████████▋                                | 75/326 [00:14<00:48,  5.23it/s]
 23%|█████████▊                                | 76/326 [00:14<00:50,  4.97it/s]
 24%|█████████▉                                | 77/326 [00:14<00:52,  4.72it/s]
 24%|██████████                                | 78/326 [00:14<00:51,  4.86it/s]
 24%|██████████▏                               | 79/326 [00:14<00:49,  4.97it/s]
 25%|██████████▎                               | 80/326 [00:15<00:48,  5.09it/s]
 25%|██████████▍                               | 81/326 [00:15<00:47,  5.15it/s]
 25%|██████████▌                               | 82/326 [00:15<00:46,  5.30it/s]
 25%|██████████▋                               | 83/326 [00:15<00:44,  5.40it/s]
 26%|██████████▊                               | 84/326 [00:15<00:45,  5.35it/s]
 26%|██████████▉                               | 85/326 [00:16<00:44,  5.36it/s]
 26%|███████████                               | 86/326 [00:16<00:44,  5.41it/s]
 27%|███████████▏                              | 87/326 [00:16<00:40,  5.95it/s]
 27%|███████████▎                              | 88/326 [00:16<00:37,  6.35it/s]
 27%|███████████▍                              | 89/326 [00:16<00:40,  5.79it/s]
 28%|███████████▌                              | 90/326 [00:16<00:43,  5.42it/s]
 28%|███████████▋                              | 91/326 [00:17<00:41,  5.61it/s]
 28%|███████████▊                              | 92/326 [00:17<00:44,  5.28it/s]
 29%|███████████▉                              | 93/326 [00:17<00:47,  4.88it/s]
 29%|████████████                              | 94/326 [00:17<00:46,  5.02it/s]
 29%|████████████▏                             | 95/326 [00:17<00:45,  5.04it/s]
 29%|████████████▎                             | 96/326 [00:18<00:44,  5.22it/s]
 30%|████████████▍                             | 97/326 [00:18<00:41,  5.46it/s]
 30%|████████████▋                             | 98/326 [00:18<00:40,  5.64it/s]
 30%|████████████▊                             | 99/326 [00:18<00:41,  5.48it/s]
 31%|████████████▌                            | 100/326 [00:18<00:42,  5.37it/s]
 31%|████████████▋                            | 101/326 [00:19<00:42,  5.29it/s]
 31%|████████████▊                            | 102/326 [00:19<00:43,  5.17it/s]
 32%|████████████▉                            | 103/326 [00:19<00:41,  5.35it/s]
 32%|█████████████                            | 104/326 [00:19<00:43,  5.12it/s]
 32%|█████████████▏                           | 105/326 [00:19<00:44,  4.93it/s]
 33%|█████████████▎                           | 106/326 [00:19<00:40,  5.48it/s]
 33%|█████████████▍                           | 107/326 [00:20<00:38,  5.62it/s]
 33%|█████████████▌                           | 108/326 [00:20<00:41,  5.27it/s]
 33%|█████████████▋                           | 109/326 [00:20<00:44,  4.85it/s]
 34%|█████████████▊                           | 110/326 [00:20<00:43,  4.93it/s]
 34%|█████████████▉                           | 111/326 [00:20<00:43,  4.97it/s]
 34%|██████████████                           | 112/326 [00:21<00:42,  5.08it/s]
 35%|██████████████▏                          | 113/326 [00:21<00:42,  4.98it/s]
 35%|██████████████▎                          | 114/326 [00:21<00:46,  4.54it/s]
 35%|██████████████▍                          | 115/326 [00:21<00:47,  4.45it/s]
 36%|██████████████▌                          | 116/326 [00:22<00:42,  4.95it/s]
 36%|██████████████▋                          | 117/326 [00:22<00:44,  4.68it/s]
 36%|██████████████▊                          | 118/326 [00:22<00:47,  4.42it/s]
 37%|██████████████▉                          | 119/326 [00:22<00:42,  4.90it/s]
 37%|███████████████                          | 120/326 [00:22<00:40,  5.15it/s]
 37%|███████████████▏                         | 121/326 [00:23<00:39,  5.21it/s]
 37%|███████████████▎                         | 122/326 [00:23<00:41,  4.94it/s]
 38%|███████████████▍                         | 123/326 [00:23<00:41,  4.87it/s]
 38%|███████████████▌                         | 124/326 [00:23<00:37,  5.41it/s]
 38%|███████████████▋                         | 125/326 [00:23<00:35,  5.63it/s]
 39%|███████████████▊                         | 126/326 [00:23<00:35,  5.65it/s]
 39%|███████████████▉                         | 127/326 [00:24<00:34,  5.71it/s]
 39%|████████████████                         | 128/326 [00:24<00:34,  5.67it/s]
 40%|████████████████▏                        | 129/326 [00:24<00:34,  5.64it/s]
 40%|████████████████▎                        | 130/326 [00:24<00:35,  5.54it/s]
 40%|████████████████▍                        | 131/326 [00:24<00:39,  4.89it/s]
 40%|████████████████▌                        | 132/326 [00:25<00:46,  4.21it/s]
 41%|████████████████▋                        | 133/326 [00:25<00:49,  3.87it/s]
 41%|████████████████▊                        | 134/326 [00:25<00:46,  4.17it/s]
 41%|████████████████▉                        | 135/326 [00:25<00:42,  4.49it/s]
 42%|█████████████████                        | 136/326 [00:26<00:38,  4.90it/s]
 42%|█████████████████▏                       | 137/326 [00:26<00:34,  5.54it/s]
 42%|█████████████████▎                       | 138/326 [00:26<00:33,  5.64it/s]
 43%|█████████████████▍                       | 139/326 [00:26<00:30,  6.13it/s]
 43%|█████████████████▌                       | 140/326 [00:26<00:28,  6.50it/s]
 43%|█████████████████▋                       | 141/326 [00:26<00:27,  6.70it/s]
 44%|█████████████████▊                       | 142/326 [00:26<00:28,  6.46it/s]
 44%|█████████████████▉                       | 143/326 [00:27<00:29,  6.21it/s]
 44%|██████████████████                       | 144/326 [00:27<00:30,  5.95it/s]
 44%|██████████████████▏                      | 145/326 [00:27<00:32,  5.59it/s]
 45%|██████████████████▎                      | 146/326 [00:27<00:35,  5.03it/s]
 45%|██████████████████▍                      | 147/326 [00:28<00:38,  4.71it/s]
 45%|██████████████████▌                      | 148/326 [00:28<00:37,  4.76it/s]
 46%|██████████████████▋                      | 149/326 [00:28<00:35,  5.05it/s]
 46%|██████████████████▊                      | 150/326 [00:28<00:31,  5.55it/s]
 46%|██████████████████▉                      | 151/326 [00:28<00:33,  5.19it/s]
 47%|███████████████████                      | 152/326 [00:29<00:37,  4.60it/s]
 47%|███████████████████▏                     | 153/326 [00:29<00:36,  4.69it/s]
 47%|███████████████████▎                     | 154/326 [00:29<00:33,  5.15it/s]
 48%|███████████████████▍                     | 155/326 [00:29<00:33,  5.13it/s]
 48%|███████████████████▌                     | 156/326 [00:29<00:32,  5.20it/s]
 48%|███████████████████▋                     | 157/326 [00:29<00:31,  5.35it/s]
 48%|███████████████████▊                     | 158/326 [00:30<00:31,  5.27it/s]
 49%|███████████████████▉                     | 159/326 [00:30<00:33,  5.06it/s]
 49%|████████████████████                     | 160/326 [00:30<00:36,  4.54it/s]
 49%|████████████████████▏                    | 161/326 [00:30<00:41,  4.00it/s]
 50%|████████████████████▎                    | 162/326 [00:31<00:40,  4.09it/s]
 50%|████████████████████▌                    | 163/326 [00:31<00:37,  4.32it/s]
 50%|████████████████████▋                    | 164/326 [00:31<00:36,  4.50it/s]
 51%|████████████████████▊                    | 165/326 [00:31<00:34,  4.61it/s]
 51%|████████████████████▉                    | 166/326 [00:31<00:32,  4.91it/s]
 51%|█████████████████████                    | 167/326 [00:32<00:29,  5.47it/s]
 52%|█████████████████████▏                   | 168/326 [00:32<00:28,  5.55it/s]
 52%|█████████████████████▎                   | 169/326 [00:32<00:28,  5.50it/s]
 52%|█████████████████████▍                   | 170/326 [00:32<00:27,  5.67it/s]
 52%|█████████████████████▌                   | 171/326 [00:32<00:25,  5.97it/s]
 53%|█████████████████████▋                   | 172/326 [00:32<00:27,  5.66it/s]
 53%|█████████████████████▊                   | 173/326 [00:33<00:28,  5.35it/s]
 53%|█████████████████████▉                   | 174/326 [00:33<00:28,  5.24it/s]
 54%|██████████████████████                   | 175/326 [00:33<00:28,  5.34it/s]
 54%|██████████████████████▏                  | 176/326 [00:33<00:27,  5.52it/s]
 85%|██████████████████████████████████▊      | 277/326 [00:53<00:09,  5.00it/s]
 85%|██████████████████████████████████▉      | 278/326 [00:53<00:09,  5.27it/s]
 86%|███████████████████████████████████      | 279/326 [00:54<00:09,  5.05it/s]
 86%|███████████████████████████████████▏     | 280/326 [00:54<00:09,  4.60it/s]
 86%|███████████████████████████████████▎     | 281/326 [00:54<00:10,  4.41it/s]
 87%|███████████████████████████████████▍     | 282/326 [00:54<00:09,  4.47it/s]
 87%|███████████████████████████████████▌     | 283/326 [00:54<00:09,  4.66it/s]
 87%|███████████████████████████████████▋     | 284/326 [00:55<00:09,  4.38it/s]
 87%|███████████████████████████████████▊     | 285/326 [00:55<00:09,  4.26it/s]
 88%|███████████████████████████████████▉     | 286/326 [00:55<00:09,  4.39it/s]
 88%|████████████████████████████████████     | 287/326 [00:55<00:09,  4.31it/s]
 88%|████████████████████████████████████▏    | 288/326 [00:56<00:08,  4.67it/s]
 89%|████████████████████████████████████▎    | 289/326 [00:56<00:07,  5.05it/s]
 89%|████████████████████████████████████▍    | 290/326 [00:56<00:06,  5.25it/s]
 89%|████████████████████████████████████▌    | 291/326 [00:56<00:06,  5.38it/s]
 90%|████████████████████████████████████▋    | 292/326 [00:56<00:06,  5.29it/s]
 90%|████████████████████████████████████▊    | 293/326 [00:56<00:06,  5.42it/s]
 90%|████████████████████████████████████▉    | 294/326 [00:57<00:05,  5.51it/s]
 90%|█████████████████████████████████████    | 295/326 [00:57<00:06,  4.99it/s]
 91%|█████████████████████████████████████▏   | 296/326 [00:57<00:06,  4.77it/s]
 91%|█████████████████████████████████████▎   | 297/326 [00:57<00:05,  5.40it/s]
 91%|█████████████████████████████████████▍   | 298/326 [00:57<00:05,  5.50it/s]
 92%|█████████████████████████████████████▌   | 299/326 [00:58<00:04,  5.99it/s]
 92%|█████████████████████████████████████▋   | 300/326 [00:58<00:04,  6.12it/s]
 92%|█████████████████████████████████████▊   | 301/326 [00:58<00:03,  6.39it/s]
 93%|█████████████████████████████████████▉   | 302/326 [00:58<00:04,  5.83it/s]
 93%|██████████████████████████████████████   | 303/326 [00:58<00:04,  5.62it/s]
 93%|██████████████████████████████████████▏  | 304/326 [00:58<00:03,  5.82it/s]
 94%|██████████████████████████████████████▎  | 305/326 [00:59<00:03,  5.80it/s]
 94%|██████████████████████████████████████▍  | 306/326 [00:59<00:03,  5.78it/s]
 94%|██████████████████████████████████████▌  | 307/326 [00:59<00:03,  6.02it/s]
 94%|██████████████████████████████████████▋  | 308/326 [00:59<00:03,  5.95it/s]
 95%|██████████████████████████████████████▊  | 309/326 [00:59<00:03,  5.50it/s]
 95%|██████████████████████████████████████▉  | 310/326 [00:59<00:02,  5.53it/s]

In [31]:
!cat results/E3_adaptive50_random_results.json

{
  "experiment_id": "E3",
  "experiment_name": "adaptive50_random_order",
  "config_path": "configs/exp3_adaptive50_random.yaml",
  "seed": 42,
  "n_train_examples": 24700,
  "n_eval_examples": 2601,
  "data_fraction": 0.5,
  "selection_method": "adaptive",
  "ordering": "random",
  "wall_clock_seconds": 1703.05,
  "wall_clock_minutes": 28.38,
  "peak_gpu_memory_mb": 6887.5,
  "system_ram": {
    "used_mb": 2818.7,
    "total_mb": 32100.1,
    "percent": 10.3
  },
  "trainable_params": 4399104,
  "total_params": 498431872,
  "trainable_pct": 0.8826,
  "eval_loss": 1.2046293020248413,
  "eval_runtime": 63.4395,
  "eval_samples_per_second": 41.0,
  "eval_steps_per_second": 5.139,
  "epoch": 1.0,
  "train_loss": 1.1542563734894589
}

In [32]:
# E4 — Full Method: Adaptive 50% + Curriculum (easy->hard, 3 epochs)
!python src/train_baseline.py --config configs/exp4_adaptive50_curriculum.yaml

2026-08-21 01:23:09 | INFO     | train | === Experiment E4: adaptive50_curriculum | seed=42 ===
2026-08-21 01:23:09 | INFO     | train | Config: configs/exp4_adaptive50_curriculum.yaml
2026-08-21 01:23:09 | INFO     | train | GPU free at experiment start: 14.36 GB / 14.56 GB
2026-08-21 01:23:10 | INFO     | data_utils | Loading dataset: tatsu-lab/alpaca
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-08-21 01:23:10 | INFO     | data_utils | Train: 49401, Eval: 2601
2026-08-21 01:23:14 | INFO     | train | Loading cached scores from data/scored_alpaca.json
2026-08-21 01:23:14 | INFO     | select_and_order | Selection: method=adaptive, fraction=0.5, n_total=49401
2026-08-21 01:23:14 | INFO     | select_and_order | Selected 24700 / 49401 examples (50.0%)
2026-08-21 01:23:14 | INFO     | select_and_order | Curriculum ordering applied: easy→hard by complexity sub-score
2026-08-21 01:23:14 | INFO     | train | Training on 24700 examples
Skipping import of cpp extensions due to incompatible torch version. Please upgrade to torch >= 2.11.0 (found 2.10.0+cu128).
2026-08-21 01:23:20 | INFO     | train | Loading model: Qwen/Qwen2.5-0.5B-Instruct
Loading weights: 100%|█| 290/290 [00:00<00:00, 1452.63it/s, Materializing param=
trainable params: 4,399,104 || all params: 498,431,872 || trainable%: 0.8826
2026-08-21 01:23:23 | INFO     | train | Trainable params: 4,399,104 (0.88% of 498,431,872)
Tokenising: 100%|████████████████| 24700/24700 [00:03<00:00, 6695.49 examples/s]
Tokenising: 100%|██████████████████| 2601/2601 [00:00<00:00, 5871.06 examples/s]
2026-08-21 01:23:31 | INFO     | train | Training started ...
{'loss': '1.396', 'grad_norm': '0.5732', 'learning_rate': '0.0001994', 'epoch': '0.06477'}
{'loss': '1.171', 'grad_norm': '0.5057', 'learning_rate': '0.0001951', 'epoch': '0.1295'}
{'loss': '1.155', 'grad_norm': '0.4762', 'learning_rate': '0.0001865', 'epoch': '0.1943'}
{'loss': '1.136', 'grad_norm': '0.4748', 'learning_rate': '0.0001742', 'epoch': '0.2591'}
{'loss': '1.129', 'grad_norm': '0.4649', 'learning_rate': '0.0001586', 'epoch': '0.3238'}
{'loss': '1.139', 'grad_norm': '0.4691', 'learning_rate': '0.0001404', 'epoch': '0.3886'}
{'loss': '1.129', 'grad_norm': '0.4507', 'learning_rate': '0.0001204', 'epoch': '0.4534'}
{'loss': '1.147', 'grad_norm': '0.478', 'learning_rate': '9.958e-05', 'epoch': '0.5181'}
{'loss': '1.134', 'grad_norm': '0.4866', 'learning_rate': '7.874e-05', 'epoch': '0.5829'}
{'loss': '1.141', 'grad_norm': '0.4339', 'learning_rate': '5.884e-05', 'epoch': '0.6477'}
{'loss': '1.132', 'grad_norm': '0.4649', 'learning_rate': '4.075e-05', 'epoch': '0.7124'}
{'loss': '1.12', 'grad_norm': '0.4382', 'learning_rate': '2.526e-05', 'epoch': '0.7772'}
{'loss': '1.14', 'grad_norm': '0.48', 'learning_rate': '1.305e-05', 'epoch': '0.842'}
{'loss': '1.126', 'grad_norm': '0.4772', 'learning_rate': '4.663e-06', 'epoch': '0.9067'}
{'loss': '1.126', 'grad_norm': '0.4638', 'learning_rate': '4.662e-07', 'epoch': '0.9715'}
100%|█████████████████████████████████████████| 772/772 [27:21<00:00,  2.07s/it]
  0%|                                                   | 0/326 [00:00<?, ?it/s]
  1%|▎                                          | 2/326 [00:00<00:23, 13.81it/s]
  1%|▌                                          | 4/326 [00:00<00:48,  6.60it/s]
  2%|▋                                          | 5/326 [00:00<01:01,  5.24it/s]
  2%|▊                                          | 6/326 [00:01<00:59,  5.36it/s]
  2%|▉                                          | 7/326 [00:01<01:01,  5.17it/s]
  2%|█                                          | 8/326 [00:01<00:59,  5.31it/s]
  3%|█▏                                         | 9/326 [00:01<00:55,  5.68it/s]
  3%|█▎                                        | 10/326 [00:01<00:56,  5.57it/s]
  3%|█▍                                        | 11/326 [00:01<00:49,  6.31it/s]
  4%|█▌                                        | 12/326 [00:01<00:47,  6.65it/s]
  4%|█▋                                        | 13/326 [00:02<00:44,  7.00it/s]
  4%|█▊                                        | 14/326 [00:02<00:45,  6.84it/s]
  5%|█▉                                        | 15/326 [00:02<00:48,  6.45it/s]
  5%|██                                        | 16/326 [00:02<00:51,  6.05it/s]
  5%|██▏                                       | 17/326 [00:02<00:53,  5.75it/s]
  6%|██▎                                       | 18/326 [00:03<01:03,  4.85it/s]
  6%|██▍                                       | 19/326 [00:03<01:11,  4.31it/s]
  6%|██▌                                       | 20/326 [00:03<01:04,  4.73it/s]
  6%|██▋                                       | 21/326 [00:03<00:58,  5.23it/s]
  7%|██▊                                       | 22/326 [00:03<00:52,  5.80it/s]
  7%|██▉                                       | 23/326 [00:04<00:53,  5.61it/s]
  7%|███                                       | 24/326 [00:04<00:54,  5.56it/s]
  8%|███▏                                      | 25/326 [00:04<00:51,  5.88it/s]
  8%|███▎                                      | 26/326 [00:04<00:49,  6.07it/s]
  8%|███▍                                      | 27/326 [00:04<00:53,  5.57it/s]
  9%|███▌                                      | 28/326 [00:04<00:57,  5.22it/s]
  9%|███▋                                      | 29/326 [00:05<00:53,  5.59it/s]
  9%|███▊                                      | 30/326 [00:05<00:50,  5.85it/s]
 10%|███▉                                      | 31/326 [00:05<00:50,  5.80it/s]
 10%|████                                      | 32/326 [00:05<00:50,  5.82it/s]
 10%|████▎                                     | 33/326 [00:05<00:50,  5.83it/s]
 10%|████▍                                     | 34/326 [00:05<00:50,  5.74it/s]
 11%|████▌                                     | 35/326 [00:06<00:52,  5.59it/s]
 11%|████▋                                     | 36/326 [00:06<00:54,  5.33it/s]
 11%|████▊                                     | 37/326 [00:06<00:58,  4.95it/s]
 12%|████▉                                     | 38/326 [00:06<00:58,  4.96it/s]
 12%|█████                                     | 39/326 [00:06<00:57,  4.95it/s]
 12%|█████▏                                    | 40/326 [00:07<01:05,  4.37it/s]
 13%|█████▎                                    | 41/326 [00:07<01:11,  3.98it/s]
 13%|█████▍                                    | 42/326 [00:07<01:07,  4.23it/s]
 13%|█████▌                                    | 43/326 [00:07<01:02,  4.54it/s]
 13%|█████▋                                    | 44/326 [00:08<00:59,  4.75it/s]
 14%|█████▊                                    | 45/326 [00:08<00:57,  4.91it/s]
 14%|█████▉                                    | 46/326 [00:08<00:59,  4.68it/s]
 14%|██████                                    | 47/326 [00:08<01:03,  4.37it/s]
 15%|██████▏                                   | 48/326 [00:09<01:02,  4.45it/s]
 15%|██████▎                                   | 49/326 [00:09<00:59,  4.67it/s]
 15%|██████▍                                   | 50/326 [00:09<00:55,  4.96it/s]
 16%|██████▌                                   | 51/326 [00:09<00:57,  4.75it/s]
 16%|██████▋                                   | 52/326 [00:09<00:53,  5.10it/s]
 16%|██████▊                                   | 53/326 [00:09<00:50,  5.39it/s]
 17%|██████▉                                   | 54/326 [00:10<00:48,  5.62it/s]
 17%|███████                                   | 55/326 [00:10<00:43,  6.19it/s]
 17%|███████▏                                  | 56/326 [00:10<00:40,  6.59it/s]
 17%|███████▎                                  | 57/326 [00:10<00:42,  6.38it/s]
 18%|███████▍                                  | 58/326 [00:10<00:44,  5.96it/s]
 18%|███████▌                                  | 59/326 [00:10<00:47,  5.67it/s]
 18%|███████▋                                  | 60/326 [00:11<00:48,  5.43it/s]
 19%|███████▊                                  | 61/326 [00:11<00:50,  5.24it/s]
 19%|███████▉                                  | 62/326 [00:11<00:56,  4.70it/s]
 19%|████████                                  | 63/326 [00:11<01:01,  4.28it/s]
 20%|████████▏                                 | 64/326 [00:12<00:55,  4.75it/s]
 20%|████████▎                                 | 65/326 [00:12<00:52,  4.99it/s]
 20%|████████▌                                 | 66/326 [00:12<00:49,  5.28it/s]
 21%|████████▋                                 | 67/326 [00:12<00:42,  6.03it/s]
 21%|████████▊                                 | 68/326 [00:12<00:42,  6.05it/s]
 21%|████████▉                                 | 69/326 [00:12<00:46,  5.58it/s]
 21%|█████████                                 | 70/326 [00:13<00:51,  4.96it/s]
 22%|█████████▏                                | 71/326 [00:13<00:51,  4.92it/s]
 22%|█████████▎                                | 72/326 [00:13<00:51,  4.91it/s]
 22%|█████████▍                                | 73/326 [00:13<00:51,  4.91it/s]
 23%|█████████▌                                | 74/326 [00:13<00:49,  5.10it/s]
 23%|█████████▋                                | 75/326 [00:14<00:48,  5.22it/s]
 23%|█████████▊                                | 76/326 [00:14<00:50,  4.97it/s]
 24%|█████████▉                                | 77/326 [00:14<00:52,  4.72it/s]
 24%|██████████                                | 78/326 [00:14<00:50,  4.87it/s]
 24%|██████████▏                               | 79/326 [00:14<00:49,  4.96it/s]
 25%|██████████▎                               | 80/326 [00:15<00:48,  5.10it/s]
 25%|██████████▍                               | 81/326 [00:15<00:47,  5.15it/s]
 25%|██████████▌                               | 82/326 [00:15<00:45,  5.32it/s]
 25%|██████████▋                               | 83/326 [00:15<00:45,  5.40it/s]
 26%|██████████▊                               | 84/326 [00:15<00:45,  5.36it/s]
 26%|██████████▉                               | 85/326 [00:16<00:44,  5.38it/s]
 26%|███████████                               | 86/326 [00:16<00:44,  5.45it/s]
 27%|███████████▏                              | 87/326 [00:16<00:39,  6.04it/s]
 27%|███████████▎                              | 88/326 [00:16<00:37,  6.40it/s]
 27%|███████████▍                              | 89/326 [00:16<00:40,  5.81it/s]
 28%|███████████▌                              | 90/326 [00:16<00:43,  5.41it/s]
 28%|███████████▋                              | 91/326 [00:17<00:41,  5.61it/s]
 28%|███████████▊                              | 92/326 [00:17<00:44,  5.29it/s]
 29%|███████████▉                              | 93/326 [00:17<00:47,  4.88it/s]
 29%|████████████                              | 94/326 [00:17<00:46,  5.01it/s]
 29%|████████████▏                             | 95/326 [00:17<00:45,  5.05it/s]
 29%|████████████▎                             | 96/326 [00:18<00:44,  5.19it/s]
 30%|████████████▍                             | 97/326 [00:18<00:41,  5.46it/s]
 30%|████████████▋                             | 98/326 [00:18<00:40,  5.64it/s]
 30%|████████████▊                             | 99/326 [00:18<00:41,  5.50it/s]
 31%|████████████▌                            | 100/326 [00:18<00:42,  5.38it/s]
 31%|████████████▋                            | 101/326 [00:18<00:42,  5.31it/s]
 31%|████████████▊                            | 102/326 [00:19<00:43,  5.19it/s]
 32%|████████████▉                            | 103/326 [00:19<00:41,  5.35it/s]
 32%|█████████████                            | 104/326 [00:19<00:43,  5.13it/s]
 32%|█████████████▏                           | 105/326 [00:19<00:44,  4.95it/s]
 33%|█████████████▎                           | 106/326 [00:19<00:39,  5.51it/s]
 33%|█████████████▍                           | 107/326 [00:20<00:38,  5.67it/s]
 33%|█████████████▌                           | 108/326 [00:20<00:41,  5.31it/s]
 33%|█████████████▋                           | 109/326 [00:20<00:44,  4.86it/s]
 34%|█████████████▊                           | 110/326 [00:20<00:43,  4.94it/s]
 34%|█████████████▉                           | 111/326 [00:20<00:43,  4.97it/s]
 34%|██████████████                           | 112/326 [00:21<00:42,  5.07it/s]
 35%|██████████████▏                          | 113/326 [00:21<00:42,  5.00it/s]
 35%|██████████████▎                          | 114/326 [00:21<00:46,  4.58it/s]
 35%|██████████████▍                          | 115/326 [00:21<00:47,  4.47it/s]
 36%|██████████████▌                          | 116/326 [00:21<00:42,  4.99it/s]
 36%|██████████████▋                          | 117/326 [00:22<00:44,  4.72it/s]
 36%|██████████████▊                          | 118/326 [00:22<00:46,  4.44it/s]
 37%|██████████████▉                          | 119/326 [00:22<00:42,  4.91it/s]
 37%|███████████████                          | 120/326 [00:22<00:39,  5.15it/s]
 37%|███████████████▏                         | 121/326 [00:22<00:39,  5.23it/s]
 37%|███████████████▎                         | 122/326 [00:23<00:41,  4.97it/s]
 38%|███████████████▍                         | 123/326 [00:23<00:41,  4.90it/s]
 38%|███████████████▌                         | 124/326 [00:23<00:37,  5.44it/s]
 38%|███████████████▋                         | 125/326 [00:23<00:35,  5.67it/s]
 39%|███████████████▊                         | 126/326 [00:23<00:35,  5.69it/s]
 39%|███████████████▉                         | 127/326 [00:24<00:34,  5.74it/s]
 39%|████████████████                         | 128/326 [00:24<00:34,  5.71it/s]
 40%|████████████████▏                        | 129/326 [00:24<00:34,  5.67it/s]
 40%|████████████████▎                        | 130/326 [00:24<00:35,  5.57it/s]
 40%|████████████████▍                        | 131/326 [00:24<00:39,  4.90it/s]
 40%|████████████████▌                        | 132/326 [00:25<00:45,  4.23it/s]
 41%|████████████████▋                        | 133/326 [00:25<00:49,  3.89it/s]
 41%|████████████████▊                        | 134/326 [00:25<00:45,  4.18it/s]
 41%|████████████████▉                        | 135/326 [00:25<00:42,  4.50it/s]
 42%|█████████████████                        | 136/326 [00:26<00:38,  4.96it/s]
 42%|█████████████████▏                       | 137/326 [00:26<00:33,  5.59it/s]
 42%|█████████████████▎                       | 138/326 [00:26<00:32,  5.71it/s]
 43%|█████████████████▍                       | 139/326 [00:26<00:30,  6.15it/s]
 43%|█████████████████▌                       | 140/326 [00:26<00:28,  6.51it/s]
 43%|█████████████████▋                       | 141/326 [00:26<00:27,  6.75it/s]
 44%|█████████████████▊                       | 142/326 [00:26<00:28,  6.50it/s]
 44%|█████████████████▉                       | 143/326 [00:27<00:29,  6.23it/s]
 44%|██████████████████                       | 144/326 [00:27<00:30,  5.97it/s]
 44%|██████████████████▏                      | 145/326 [00:27<00:32,  5.60it/s]
 45%|██████████████████▎                      | 146/326 [00:27<00:35,  5.05it/s]
 45%|██████████████████▍                      | 147/326 [00:27<00:37,  4.74it/s]
 45%|██████████████████▌                      | 148/326 [00:28<00:37,  4.80it/s]
 46%|██████████████████▋                      | 149/326 [00:28<00:35,  5.00it/s]
 46%|██████████████████▊                      | 150/326 [00:28<00:31,  5.63it/s]
 46%|██████████████████▉                      | 151/326 [00:28<00:33,  5.26it/s]
 47%|███████████████████                      | 152/326 [00:28<00:37,  4.62it/s]
 47%|███████████████████▏                     | 153/326 [00:29<00:36,  4.71it/s]
 47%|███████████████████▎                     | 154/326 [00:29<00:33,  5.16it/s]
 48%|███████████████████▍                     | 155/326 [00:29<00:33,  5.14it/s]
 48%|███████████████████▌                     | 156/326 [00:29<00:32,  5.23it/s]
 48%|███████████████████▋                     | 157/326 [00:29<00:31,  5.39it/s]
 48%|███████████████████▊                     | 158/326 [00:30<00:31,  5.27it/s]
 49%|███████████████████▉                     | 159/326 [00:30<00:32,  5.07it/s]
 49%|████████████████████                     | 160/326 [00:30<00:36,  4.55it/s]
 49%|████████████████████▏                    | 161/326 [00:30<00:40,  4.03it/s]
 50%|████████████████████▎                    | 162/326 [00:31<00:39,  4.12it/s]
 50%|████████████████████▌                    | 163/326 [00:31<00:37,  4.35it/s]
 50%|████████████████████▋                    | 164/326 [00:31<00:35,  4.53it/s]
 51%|████████████████████▊                    | 165/326 [00:31<00:34,  4.64it/s]
 51%|████████████████████▉                    | 166/326 [00:31<00:32,  4.91it/s]
 51%|█████████████████████                    | 167/326 [00:31<00:29,  5.48it/s]
 52%|█████████████████████▏                   | 168/326 [00:32<00:28,  5.58it/s]
 52%|█████████████████████▎                   | 169/326 [00:32<00:28,  5.54it/s]
 52%|█████████████████████▍                   | 170/326 [00:32<00:27,  5.68it/s]
 52%|█████████████████████▌                   | 171/326 [00:32<00:25,  5.99it/s]
 53%|█████████████████████▋                   | 172/326 [00:32<00:27,  5.68it/s]
 53%|█████████████████████▊                   | 173/326 [00:33<00:28,  5.37it/s]
 53%|█████████████████████▉                   | 174/326 [00:33<00:28,  5.28it/s]
 54%|██████████████████████                   | 175/326 [00:33<00:28,  5.38it/s]
 54%|██████████████████████▏                  | 176/326 [00:33<00:26,  5.58it/s]
 54%|██████████████████████▎                  | 177/326 [00:33<00:29,  4.97it/s]
 55%|██████████████████████▍                  | 178/326 [00:34<00:34,  4.30it/s]
 55%|██████████████████████▌                  | 179/326 [00:34<00:31,  4.65it/s]
 55%|██████████████████████▋                  | 180/326 [00:34<00:32,  4.44it/s]
 56%|██████████████████████▊                  | 181/326 [00:34<00:35,  4.11it/s]
 56%|██████████████████████▉                  | 182/326 [00:35<00:32,  4.37it/s]
 56%|███████████████████████                  | 183/326 [00:35<00:32,  4.44it/s]
 56%|███████████████████████▏                 | 184/326 [00:35<00:29,  4.87it/s]
 57%|███████████████████████▎                 | 185/326 [00:35<00:26,  5.25it/s]
 57%|███████████████████████▍                 | 186/326 [00:35<00:25,  5.59it/s]
 57%|███████████████████████▌                 | 187/326 [00:35<00:24,  5.66it/s]
 58%|███████████████████████▋                 | 188/326 [00:36<00:25,  5.36it/s]
 58%|███████████████████████▊                 | 189/326 [00:36<00:26,  5.22it/s]
 58%|███████████████████████▉                 | 190/326 [00:36<00:25,  5.30it/s]
 59%|████████████████████████                 | 191/326 [00:36<00:26,  5.12it/s]
 59%|████████████████████████▏                | 192/326 [00:36<00:26,  5.04it/s]
 59%|████████████████████████▎                | 193/326 [00:37<00:26,  4.98it/s]
 60%|████████████████████████▍                | 194/326 [00:37<00:26,  4.94it/s]
 60%|████████████████████████▌                | 195/326 [00:37<00:26,  4.94it/s]
 60%|████████████████████████▋                | 196/326 [00:37<00:27,  4.75it/s]
 60%|████████████████████████▊                | 197/326 [00:38<00:29,  4.31it/s]
 61%|████████████████████████▉                | 198/326 [00:38<00:27,  4.71it/s]
 61%|█████████████████████████                | 199/326 [00:38<00:25,  4.99it/s]
 61%|█████████████████████████▏               | 200/326 [00:38<00:23,  5.48it/s]
 62%|█████████████████████████▎               | 201/326 [00:38<00:22,  5.51it/s]
 62%|█████████████████████████▍               | 202/326 [00:38<00:22,  5.57it/s]
 62%|█████████████████████████▌               | 203/326 [00:39<00:22,  5.44it/s]
 63%|█████████████████████████▋               | 204/326 [00:39<00:24,  4.98it/s]
 63%|█████████████████████████▊               | 205/326 [00:39<00:24,  4.92it/s]
 63%|█████████████████████████▉               | 206/326 [00:39<00:24,  4.84it/s]
 63%|██████████████████████████               | 207/326 [00:39<00:25,  4.69it/s]
 64%|██████████████████████████▏              | 208/326 [00:40<00:24,  4.86it/s]
 64%|██████████████████████████▎              | 209/326 [00:40<00:24,  4.80it/s]

In [33]:
cat outputs/E4_adaptive50_curriculum/results.json

{
  "experiment_id": "E4",
  "experiment_name": "adaptive50_curriculum",
  "config_path": "configs/exp4_adaptive50_curriculum.yaml",
  "seed": 42,
  "n_train_examples": 24700,
  "n_eval_examples": 2601,
  "data_fraction": 0.5,
  "selection_method": "adaptive",
  "ordering": "curriculum",
  "wall_clock_seconds": 1706.23,
  "wall_clock_minutes": 28.44,
  "peak_gpu_memory_mb": 6887.5,
  "system_ram": {
    "used_mb": 2841.9,
    "total_mb": 32100.1,
    "percent": 10.4
  },
  "trainable_params": 4399104,
  "total_params": 498431872,
  "trainable_pct": 0.8826,
  "eval_loss": 1.2041741609573364,
  "eval_runtime": 63.2834,
  "eval_samples_per_second": 41.101,
  "eval_steps_per_second": 5.151,
  "epoch": 1.0,
  "train_loss": 1.154269584102334
}

In [36]:

# E5 — Random 50% + Curriculum (isolation test, 3 epochs)
!python src/train_baseline.py --config configs/exp5_random50_curriculum.yaml

2026-08-21 01:56:44 | INFO     | train | === Experiment E5: random50_curriculum | seed=42 ===
2026-08-21 01:56:44 | INFO     | train | Config: configs/exp5_random50_curriculum.yaml
2026-08-21 01:56:44 | INFO     | train | GPU free at experiment start: 14.36 GB / 14.56 GB
2026-08-21 01:56:45 | INFO     | data_utils | Loading dataset: tatsu-lab/alpaca
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-08-21 01:56:46 | INFO     | data_utils | Train: 49401, Eval: 2601
2026-08-21 01:56:49 | INFO     | train | Loading cached scores from data/scored_alpaca.json
2026-08-21 01:56:49 | INFO     | select_and_order | Selection: method=random, fraction=0.5, n_total=49401
2026-08-21 01:56:49 | INFO     | select_and_order | Selected 24700 / 49401 examples (50.0%)
2026-08-21 01:56:49 | INFO     | select_and_order | Curriculum ordering applied: easy→hard by complexity sub-score
2026-08-21 01:56:50 | INFO     | train | Training on 24700 examples
Skipping import of cpp extensions due to incompatible torch version. Please upgrade to torch >= 2.11.0 (found 2.10.0+cu128).
2026-08-21 01:56:55 | INFO     | train | Loading model: Qwen/Qwen2.5-0.5B-Instruct
Loading weights: 100%|█| 290/290 [00:00<00:00, 1631.97it/s, Materializing param=
trainable params: 4,399,104 || all params: 498,431,872 || trainable%: 0.8826
2026-08-21 01:56:58 | INFO     | train | Trainable params: 4,399,104 (0.88% of 498,431,872)
Tokenising: 100%|████████████████| 24700/24700 [00:03<00:00, 6278.63 examples/s]
Tokenising: 100%|██████████████████| 2601/2601 [00:00<00:00, 6006.42 examples/s]
2026-08-21 01:57:06 | INFO     | train | Training started ...
{'loss': '1.473', 'grad_norm': '0.519', 'learning_rate': '0.0001994', 'epoch': '0.06477'}
{'loss': '1.243', 'grad_norm': '0.5344', 'learning_rate': '0.0001951', 'epoch': '0.1295'}
{'loss': '1.241', 'grad_norm': '0.4743', 'learning_rate': '0.0001865', 'epoch': '0.1943'}
{'loss': '1.215', 'grad_norm': '0.5641', 'learning_rate': '0.0001742', 'epoch': '0.2591'}
{'loss': '1.222', 'grad_norm': '0.4465', 'learning_rate': '0.0001586', 'epoch': '0.3238'}
{'loss': '1.234', 'grad_norm': '0.4204', 'learning_rate': '0.0001404', 'epoch': '0.3886'}
{'loss': '1.223', 'grad_norm': '0.4689', 'learning_rate': '0.0001204', 'epoch': '0.4534'}
{'loss': '1.213', 'grad_norm': '0.4251', 'learning_rate': '9.958e-05', 'epoch': '0.5181'}
{'loss': '1.212', 'grad_norm': '0.4771', 'learning_rate': '7.874e-05', 'epoch': '0.5829'}
{'loss': '1.205', 'grad_norm': '0.4428', 'learning_rate': '5.884e-05', 'epoch': '0.6477'}
{'loss': '1.221', 'grad_norm': '0.4377', 'learning_rate': '4.075e-05', 'epoch': '0.7124'}
{'loss': '1.219', 'grad_norm': '0.4462', 'learning_rate': '2.526e-05', 'epoch': '0.7772'}
{'loss': '1.217', 'grad_norm': '0.4735', 'learning_rate': '1.305e-05', 'epoch': '0.842'}
{'loss': '1.209', 'grad_norm': '0.4733', 'learning_rate': '4.663e-06', 'epoch': '0.9067'}
{'loss': '1.209', 'grad_norm': '0.4781', 'learning_rate': '4.662e-07', 'epoch': '0.9715'}
100%|█████████████████████████████████████████| 772/772 [32:10<00:00,  2.24s/it]
  0%|                                                   | 0/326 [00:00<?, ?it/s]
  1%|▎                                          | 2/326 [00:00<00:23, 14.08it/s]
  1%|▌                                          | 4/326 [00:00<00:48,  6.62it/s]
  2%|▋                                          | 5/326 [00:00<01:01,  5.23it/s]
  2%|▊                                          | 6/326 [00:01<00:59,  5.38it/s]
  2%|▉                                          | 7/326 [00:01<01:01,  5.20it/s]
  2%|█                                          | 8/326 [00:01<00:59,  5.32it/s]
  3%|█▏                                         | 9/326 [00:01<00:55,  5.69it/s]
  3%|█▎                                        | 10/326 [00:01<00:56,  5.58it/s]
  3%|█▍                                        | 11/326 [00:01<00:49,  6.31it/s]
  4%|█▌                                        | 12/326 [00:01<00:46,  6.68it/s]
  4%|█▋                                        | 13/326 [00:02<00:44,  7.03it/s]
  4%|█▊                                        | 14/326 [00:02<00:45,  6.86it/s]
  5%|█▉                                        | 15/326 [00:02<00:48,  6.47it/s]
  5%|██                                        | 16/326 [00:02<00:51,  6.04it/s]
  5%|██▏                                       | 17/326 [00:02<00:53,  5.73it/s]
  6%|██▎                                       | 18/326 [00:03<01:03,  4.83it/s]
  6%|██▍                                       | 19/326 [00:03<01:11,  4.31it/s]
  6%|██▌                                       | 20/326 [00:03<01:04,  4.72it/s]
  6%|██▋                                       | 21/326 [00:03<00:58,  5.21it/s]
  7%|██▊                                       | 22/326 [00:03<00:52,  5.80it/s]
  7%|██▉                                       | 23/326 [00:04<00:53,  5.65it/s]
  7%|███                                       | 24/326 [00:04<00:54,  5.57it/s]
  8%|███▏                                      | 25/326 [00:04<00:51,  5.80it/s]
  8%|███▎                                      | 26/326 [00:04<00:48,  6.13it/s]
  8%|███▍                                      | 27/326 [00:04<00:53,  5.63it/s]
  9%|███▌                                      | 28/326 [00:04<00:56,  5.26it/s]
  9%|███▋                                      | 29/326 [00:05<00:52,  5.61it/s]
  9%|███▊                                      | 30/326 [00:05<00:50,  5.88it/s]
 10%|███▉                                      | 31/326 [00:05<00:50,  5.82it/s]
 10%|████                                      | 32/326 [00:05<00:50,  5.83it/s]
 10%|████▎                                     | 33/326 [00:05<00:50,  5.82it/s]
 10%|████▍                                     | 34/326 [00:05<00:50,  5.74it/s]
 11%|████▌                                     | 35/326 [00:06<00:51,  5.60it/s]
 11%|████▋                                     | 36/326 [00:06<00:54,  5.32it/s]
 11%|████▊                                     | 37/326 [00:06<00:58,  4.94it/s]
 12%|████▉                                     | 38/326 [00:06<00:58,  4.94it/s]
 12%|█████                                     | 39/326 [00:06<00:57,  4.96it/s]
 12%|█████▏                                    | 40/326 [00:07<01:05,  4.36it/s]
 13%|█████▎                                    | 41/326 [00:07<01:11,  3.98it/s]
 13%|█████▍                                    | 42/326 [00:07<01:07,  4.20it/s]
 13%|█████▌                                    | 43/326 [00:07<01:02,  4.50it/s]
 13%|█████▋                                    | 44/326 [00:08<00:59,  4.72it/s]
 14%|█████▊                                    | 45/326 [00:08<00:57,  4.91it/s]
 14%|█████▉                                    | 46/326 [00:08<00:59,  4.67it/s]
 14%|██████                                    | 47/326 [00:08<01:04,  4.35it/s]
 15%|██████▏                                   | 48/326 [00:09<01:02,  4.43it/s]
 15%|██████▎                                   | 49/326 [00:09<00:59,  4.68it/s]
 15%|██████▍                                   | 50/326 [00:09<00:55,  4.96it/s]
 16%|██████▌                                   | 51/326 [00:09<00:57,  4.75it/s]
 16%|██████▋                                   | 52/326 [00:09<00:53,  5.12it/s]
 16%|██████▊                                   | 53/326 [00:09<00:50,  5.40it/s]
 17%|██████▉                                   | 54/326 [00:10<00:48,  5.60it/s]
 17%|███████                                   | 55/326 [00:10<00:43,  6.19it/s]
 17%|███████▏                                  | 56/326 [00:10<00:41,  6.54it/s]
 17%|███████▎                                  | 57/326 [00:10<00:42,  6.36it/s]
 18%|███████▍                                  | 58/326 [00:10<00:45,  5.93it/s]
 18%|███████▌                                  | 59/326 [00:10<00:47,  5.64it/s]
 18%|███████▋                                  | 60/326 [00:11<00:48,  5.45it/s]
 19%|███████▊                                  | 61/326 [00:11<00:50,  5.23it/s]
 19%|███████▉                                  | 62/326 [00:11<00:56,  4.70it/s]
 19%|████████                                  | 63/326 [00:11<01:01,  4.27it/s]
 20%|████████▏                                 | 64/326 [00:12<00:55,  4.74it/s]
 20%|████████▎                                 | 65/326 [00:12<00:52,  4.99it/s]
 20%|████████▌                                 | 66/326 [00:12<00:49,  5.23it/s]
 21%|████████▋                                 | 67/326 [00:12<00:42,  6.03it/s]
 21%|████████▊                                 | 68/326 [00:12<00:42,  6.03it/s]
 21%|████████▉                                 | 69/326 [00:12<00:45,  5.60it/s]
 21%|█████████                                 | 70/326 [00:13<00:51,  4.96it/s]
 22%|█████████▏                                | 71/326 [00:13<00:51,  4.94it/s]
 22%|█████████▎                                | 72/326 [00:13<00:51,  4.91it/s]
 22%|█████████▍                                | 73/326 [00:13<00:51,  4.92it/s]
 23%|█████████▌                                | 74/326 [00:13<00:49,  5.09it/s]
 23%|█████████▋                                | 75/326 [00:14<00:48,  5.21it/s]
 23%|█████████▊                                | 76/326 [00:14<00:50,  4.96it/s]
 24%|█████████▉                                | 77/326 [00:14<00:52,  4.72it/s]
 24%|██████████                                | 78/326 [00:14<00:50,  4.87it/s]
 24%|██████████▏                               | 79/326 [00:14<00:49,  4.97it/s]
 25%|██████████▎                               | 80/326 [00:15<00:48,  5.10it/s]
 25%|██████████▍                               | 81/326 [00:15<00:47,  5.15it/s]
 25%|██████████▌                               | 82/326 [00:15<00:45,  5.32it/s]
 25%|██████████▋                               | 83/326 [00:15<00:44,  5.41it/s]
 26%|██████████▊                               | 84/326 [00:15<00:45,  5.36it/s]
 26%|██████████▉                               | 85/326 [00:16<00:44,  5.39it/s]
 26%|███████████                               | 86/326 [00:16<00:43,  5.46it/s]
 27%|███████████▏                              | 87/326 [00:16<00:39,  6.03it/s]
 27%|███████████▎                              | 88/326 [00:16<00:37,  6.42it/s]
 27%|███████████▍                              | 89/326 [00:16<00:40,  5.82it/s]
 28%|███████████▌                              | 90/326 [00:16<00:43,  5.40it/s]
 28%|███████████▋                              | 91/326 [00:17<00:42,  5.57it/s]
 28%|███████████▊                              | 92/326 [00:17<00:44,  5.29it/s]
 29%|███████████▉                              | 93/326 [00:17<00:47,  4.87it/s]
 29%|████████████                              | 94/326 [00:17<00:46,  4.99it/s]
 29%|████████████▏                             | 95/326 [00:17<00:45,  5.03it/s]
 29%|████████████▎                             | 96/326 [00:18<00:44,  5.20it/s]
 30%|████████████▍                             | 97/326 [00:18<00:42,  5.44it/s]
 30%|████████████▋                             | 98/326 [00:18<00:40,  5.69it/s]
 30%|████████████▊                             | 99/326 [00:18<00:41,  5.50it/s]
 31%|████████████▌                            | 100/326 [00:18<00:41,  5.39it/s]
 31%|████████████▋                            | 101/326 [00:18<00:42,  5.30it/s]
 31%|████████████▊                            | 102/326 [00:19<00:43,  5.19it/s]
 32%|████████████▉                            | 103/326 [00:19<00:41,  5.36it/s]
 32%|█████████████                            | 104/326 [00:19<00:43,  5.12it/s]
 32%|█████████████▏                           | 105/326 [00:19<00:44,  4.95it/s]
 33%|█████████████▎                           | 106/326 [00:19<00:40,  5.49it/s]
 33%|█████████████▍                           | 107/326 [00:20<00:38,  5.65it/s]
 33%|█████████████▌                           | 108/326 [00:20<00:41,  5.30it/s]
 33%|█████████████▋                           | 109/326 [00:20<00:44,  4.86it/s]
 34%|█████████████▊                           | 110/326 [00:20<00:43,  4.94it/s]
 34%|█████████████▉                           | 111/326 [00:20<00:43,  4.98it/s]
 34%|██████████████                           | 112/326 [00:21<00:41,  5.10it/s]
 35%|██████████████▏                          | 113/326 [00:21<00:42,  5.01it/s]
 35%|██████████████▎                          | 114/326 [00:21<00:46,  4.60it/s]
 35%|██████████████▍                          | 115/326 [00:21<00:46,  4.51it/s]
 36%|██████████████▌                          | 116/326 [00:21<00:41,  5.01it/s]
 36%|██████████████▋                          | 117/326 [00:22<00:44,  4.74it/s]
 36%|██████████████▊                          | 118/326 [00:22<00:46,  4.49it/s]
 37%|██████████████▉                          | 119/326 [00:22<00:41,  4.95it/s]
 37%|███████████████                          | 120/326 [00:22<00:39,  5.19it/s]
 37%|███████████████▏                         | 121/326 [00:22<00:39,  5.25it/s]
 37%|███████████████▎                         | 122/326 [00:23<00:40,  4.98it/s]
 38%|███████████████▍                         | 123/326 [00:23<00:41,  4.88it/s]
 38%|███████████████▌                         | 124/326 [00:23<00:36,  5.47it/s]
 38%|███████████████▋                         | 125/326 [00:23<00:35,  5.68it/s]
 39%|███████████████▊                         | 126/326 [00:23<00:35,  5.68it/s]
 39%|███████████████▉                         | 127/326 [00:24<00:34,  5.75it/s]
 39%|████████████████                         | 128/326 [00:24<00:34,  5.72it/s]
 40%|████████████████▏                        | 129/326 [00:24<00:34,  5.68it/s]
 40%|████████████████▎                        | 130/326 [00:24<00:35,  5.59it/s]
 40%|████████████████▍                        | 131/326 [00:24<00:39,  4.91it/s]
 40%|████████████████▌                        | 132/326 [00:25<00:45,  4.23it/s]
 41%|████████████████▋                        | 133/326 [00:25<00:49,  3.90it/s]
 41%|████████████████▊                        | 134/326 [00:25<00:45,  4.20it/s]
 41%|████████████████▉                        | 135/326 [00:25<00:42,  4.52it/s]
 42%|█████████████████                        | 136/326 [00:26<00:38,  4.95it/s]
 42%|█████████████████▏                       | 137/326 [00:26<00:33,  5.61it/s]
 42%|█████████████████▎                       | 138/326 [00:26<00:32,  5.70it/s]
 43%|█████████████████▍                       | 139/326 [00:26<00:30,  6.14it/s]
 43%|█████████████████▌                       | 140/326 [00:26<00:28,  6.55it/s]
 43%|█████████████████▋                       | 141/326 [00:26<00:27,  6.72it/s]
 44%|█████████████████▊                       | 142/326 [00:26<00:28,  6.50it/s]
 44%|█████████████████▉                       | 143/326 [00:27<00:29,  6.22it/s]
 44%|██████████████████                       | 144/326 [00:27<00:30,  5.96it/s]
 44%|██████████████████▏                      | 145/326 [00:27<00:32,  5.59it/s]
 45%|██████████████████▎                      | 146/326 [00:27<00:35,  5.04it/s]
 45%|██████████████████▍                      | 147/326 [00:27<00:37,  4.72it/s]
 45%|██████████████████▌                      | 148/326 [00:28<00:37,  4.79it/s]
 46%|██████████████████▋                      | 149/326 [00:28<00:34,  5.06it/s]
 46%|██████████████████▊                      | 150/326 [00:28<00:31,  5.59it/s]
 46%|██████████████████▉                      | 151/326 [00:28<00:33,  5.21it/s]
 47%|███████████████████                      | 152/326 [00:28<00:37,  4.62it/s]
 47%|███████████████████▏                     | 153/326 [00:29<00:36,  4.71it/s]
 47%|███████████████████▎                     | 154/326 [00:29<00:33,  5.18it/s]
 48%|███████████████████▍                     | 155/326 [00:29<00:33,  5.16it/s]
 48%|███████████████████▌                     | 156/326 [00:29<00:32,  5.23it/s]
 48%|███████████████████▋                     | 157/326 [00:29<00:31,  5.40it/s]
 48%|███████████████████▊                     | 158/326 [00:30<00:31,  5.29it/s]
 49%|███████████████████▉                     | 159/326 [00:30<00:32,  5.09it/s]
 49%|████████████████████                     | 160/326 [00:30<00:36,  4.56it/s]
 49%|████████████████████▏                    | 161/326 [00:30<00:40,  4.05it/s]
 50%|████████████████████▎                    | 162/326 [00:31<00:39,  4.13it/s]
 50%|████████████████████▌                    | 163/326 [00:31<00:37,  4.36it/s]
 50%|████████████████████▋                    | 164/326 [00:31<00:35,  4.54it/s]
 51%|████████████████████▊                    | 165/326 [00:31<00:34,  4.64it/s]
 51%|████████████████████▉                    | 166/326 [00:31<00:32,  4.92it/s]
 51%|█████████████████████                    | 167/326 [00:31<00:28,  5.49it/s]
 52%|█████████████████████▏                   | 168/326 [00:32<00:28,  5.58it/s]
 52%|█████████████████████▎                   | 169/326 [00:32<00:28,  5.53it/s]
 52%|█████████████████████▍                   | 170/326 [00:32<00:27,  5.69it/s]
 52%|█████████████████████▌                   | 171/326 [00:32<00:25,  6.00it/s]
 53%|█████████████████████▋                   | 172/326 [00:32<00:27,  5.68it/s]
 53%|█████████████████████▊                   | 173/326 [00:33<00:28,  5.36it/s]
 53%|█████████████████████▉                   | 174/326 [00:33<00:28,  5.27it/s]
 54%|██████████████████████                   | 175/326 [00:33<00:27,  5.40it/s]
 54%|██████████████████████▏                  | 176/326 [00:33<00:26,  5.57it/s]
 54%|██████████████████████▎                  | 177/326 [00:33<00:30,  4.96it/s]
 55%|██████████████████████▍                  | 178/326 [00:34<00:34,  4.30it/s]
 55%|██████████████████████▌                  | 179/326 [00:34<00:31,  4.65it/s]
 55%|██████████████████████▋                  | 180/326 [00:34<00:32,  4.43it/s]
 56%|██████████████████████▊                  | 181/326 [00:34<00:35,  4.10it/s]
 56%|██████████████████████▉                  | 182/326 [00:35<00:32,  4.37it/s]
 56%|███████████████████████                  | 183/326 [00:35<00:32,  4.44it/s]
 56%|███████████████████████▏                 | 184/326 [00:35<00:29,  4.87it/s]
 57%|███████████████████████▎                 | 185/326 [00:35<00:26,  5.25it/s]
 57%|███████████████████████▍                 | 186/326 [00:35<00:25,  5.55it/s]
 57%|███████████████████████▌                 | 187/326 [00:35<00:24,  5.66it/s]
 58%|███████████████████████▋                 | 188/326 [00:36<00:25,  5.36it/s]
 58%|███████████████████████▊                 | 189/326 [00:36<00:26,  5.23it/s]
 58%|███████████████████████▉                 | 190/326 [00:36<00:25,  5.29it/s]
 59%|████████████████████████                 | 191/326 [00:36<00:26,  5.14it/s]
 59%|████████████████████████▏                | 192/326 [00:36<00:26,  5.05it/s]
 59%|████████████████████████▎                | 193/326 [00:37<00:26,  4.99it/s]
 60%|████████████████████████▍                | 194/326 [00:37<00:26,  4.95it/s]
 60%|████████████████████████▌                | 195/326 [00:37<00:26,  4.97it/s]
 60%|████████████████████████▋                | 196/326 [00:37<00:27,  4.75it/s]
 60%|████████████████████████▊                | 197/326 [00:38<00:29,  4.31it/s]
 61%|████████████████████████▉                | 198/326 [00:38<00:27,  4.73it/s]
 61%|█████████████████████████                | 199/326 [00:38<00:24,  5.15it/s]
 61%|█████████████████████████▏               | 200/326 [00:38<00:23,  5.42it/s]
 62%|█████████████████████████▎               | 201/326 [00:38<00:22,  5.48it/s]
 62%|█████████████████████████▍               | 202/326 [00:38<00:22,  5.55it/s]
 62%|█████████████████████████▌               | 203/326 [00:39<00:22,  5.42it/s]
 63%|█████████████████████████▋               | 204/326 [00:39<00:24,  4.96it/s]
 63%|█████████████████████████▊               | 205/326 [00:39<00:24,  4.92it/s]
 63%|█████████████████████████▉               | 206/326 [00:39<00:24,  4.83it/s]
 63%|██████████████████████████               | 207/326 [00:39<00:25,  4.69it/s]
 64%|██████████████████████████▏              | 208/326 [00:40<00:24,  4.85it/s]
 64%|██████████████████████████▎              | 209/326 [00:40<00:24,  4.80it/s]

In [38]:
ls -lh outputs/*/results.json

-rw-r--r-- 1 root root 726 Aug 21 00:39 outputs/E2_random50_random/results.json
-rw-r--r-- 1 root root 740 Aug 21 01:16 outputs/E3_adaptive50_random/results.json
-rw-r--r-- 1 root root 747 Aug 21 01:53 outputs/E4_adaptive50_curriculum/results.json
-rw-r--r-- 1 root root 739 Aug 21 02:31 outputs/E5_random50_curriculum/results.json

### Step 6: Execute Ablations (A & B)

In [39]:
# Ablation A — Diversity Only (50% subset, 3 epochs)
!python src/train_baseline.py --config configs/ablation_diversity_only.yaml

# Ablation B — Complexity Only (50% subset, 3 epochs)
!python src/train_baseline.py --config configs/ablation_complexity_only.yaml

2026-08-21 02:34:51 | INFO     | train | === Experiment A1: ablation_diversity_only | seed=42 ===
2026-08-21 02:34:51 | INFO     | train | Config: configs/ablation_diversity_only.yaml
2026-08-21 02:34:51 | INFO     | train | GPU free at experiment start: 14.36 GB / 14.56 GB
2026-08-21 02:34:52 | INFO     | data_utils | Loading dataset: tatsu-lab/alpaca
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-08-21 02:34:53 | INFO     | data_utils | Train: 49401, Eval: 2601
2026-08-21 02:34:56 | INFO     | train | Loading cached scores from data/scored_alpaca.json
2026-08-21 02:34:57 | INFO     | select_and_order | Selection: method=adaptive, fraction=0.5, n_total=49401
2026-08-21 02:34:57 | INFO     | select_and_order | Selected 24700 / 49401 examples (50.0%)
2026-08-21 02:34:57 | INFO     | train | Training on 24700 examples
Skipping import of cpp extensions due to incompatible torch version. Please upgrade to torch >= 2.11.0 (found 2.10.0+cu128).
2026-08-21 02:35:03 | INFO     | train | Loading model: Qwen/Qwen2.5-0.5B-Instruct
Loading weights: 100%|█| 290/290 [00:00<00:00, 1669.51it/s, Materializing param=
trainable params: 4,399,104 || all params: 498,431,872 || trainable%: 0.8826
2026-08-21 02:35:05 | INFO     | train | Trainable params: 4,399,104 (0.88% of 498,431,872)
Tokenising: 100%|████████████████| 24700/24700 [00:03<00:00, 6731.80 examples/s]
Tokenising: 100%|██████████████████| 2601/2601 [00:00<00:00, 5944.21 examples/s]
2026-08-21 02:35:13 | INFO     | train | Training started ...
{'loss': '1.384', 'grad_norm': '0.7428', 'learning_rate': '0.0001994', 'epoch': '0.06477'}
{'loss': '1.168', 'grad_norm': '0.459', 'learning_rate': '0.0001951', 'epoch': '0.1295'}
{'loss': '1.165', 'grad_norm': '0.5327', 'learning_rate': '0.0001865', 'epoch': '0.1943'}
{'loss': '1.153', 'grad_norm': '0.4968', 'learning_rate': '0.0001742', 'epoch': '0.2591'}
{'loss': '1.137', 'grad_norm': '0.4551', 'learning_rate': '0.0001586', 'epoch': '0.3238'}
{'loss': '1.14', 'grad_norm': '0.4557', 'learning_rate': '0.0001404', 'epoch': '0.3886'}
{'loss': '1.145', 'grad_norm': '0.466', 'learning_rate': '0.0001204', 'epoch': '0.4534'}
{'loss': '1.146', 'grad_norm': '0.4549', 'learning_rate': '9.958e-05', 'epoch': '0.5181'}
{'loss': '1.124', 'grad_norm': '0.5076', 'learning_rate': '7.874e-05', 'epoch': '0.5829'}
{'loss': '1.145', 'grad_norm': '0.5135', 'learning_rate': '5.884e-05', 'epoch': '0.6477'}
{'loss': '1.119', 'grad_norm': '0.4853', 'learning_rate': '4.075e-05', 'epoch': '0.7124'}
{'loss': '1.122', 'grad_norm': '0.4861', 'learning_rate': '2.526e-05', 'epoch': '0.7772'}
{'loss': '1.125', 'grad_norm': '0.4355', 'learning_rate': '1.305e-05', 'epoch': '0.842'}
{'loss': '1.137', 'grad_norm': '0.4883', 'learning_rate': '4.663e-06', 'epoch': '0.9067'}
{'loss': '1.121', 'grad_norm': '0.45', 'learning_rate': '4.662e-07', 'epoch': '0.9715'}
100%|█████████████████████████████████████████| 772/772 [27:18<00:00,  2.02s/it]
  0%|                                                   | 0/326 [00:00<?, ?it/s]
  1%|▎                                          | 2/326 [00:00<00:21, 15.41it/s]
  1%|▌                                          | 4/326 [00:00<00:47,  6.77it/s]
  2%|▋                                          | 5/326 [00:00<01:00,  5.33it/s]
  2%|▊                                          | 6/326 [00:00<00:58,  5.44it/s]
  2%|▉                                          | 7/326 [00:01<01:00,  5.24it/s]
  2%|█                                          | 8/326 [00:01<01:00,  5.28it/s]
  3%|█▏                                         | 9/326 [00:01<00:55,  5.73it/s]
  3%|█▎                                        | 10/326 [00:01<00:56,  5.64it/s]
  3%|█▍                                        | 11/326 [00:01<00:49,  6.37it/s]
  4%|█▌                                        | 12/326 [00:01<00:47,  6.67it/s]
  4%|█▋                                        | 13/326 [00:02<00:44,  7.04it/s]
  4%|█▊                                        | 14/326 [00:02<00:45,  6.85it/s]
  5%|█▉                                        | 15/326 [00:02<00:48,  6.46it/s]
  5%|██                                        | 16/326 [00:02<00:51,  6.04it/s]
  5%|██▏                                       | 17/326 [00:02<00:53,  5.74it/s]
  6%|██▎                                       | 18/326 [00:03<01:03,  4.83it/s]
  6%|██▍                                       | 19/326 [00:03<01:11,  4.31it/s]
  6%|██▌                                       | 20/326 [00:03<01:04,  4.73it/s]
  6%|██▋                                       | 21/326 [00:03<00:58,  5.24it/s]
  7%|██▊                                       | 22/326 [00:03<00:52,  5.81it/s]
  7%|██▉                                       | 23/326 [00:03<00:53,  5.65it/s]
  7%|███                                       | 24/326 [00:04<00:54,  5.57it/s]
  8%|███▏                                      | 25/326 [00:04<00:50,  5.91it/s]
  8%|███▎                                      | 26/326 [00:04<00:49,  6.05it/s]
  8%|███▍                                      | 27/326 [00:04<00:53,  5.59it/s]
  9%|███▌                                      | 28/326 [00:04<00:57,  5.21it/s]
  9%|███▋                                      | 29/326 [00:05<00:53,  5.60it/s]
  9%|███▊                                      | 30/326 [00:05<00:50,  5.89it/s]
 10%|███▉                                      | 31/326 [00:05<00:50,  5.83it/s]
 10%|████                                      | 32/326 [00:05<00:49,  5.89it/s]
 10%|████▎                                     | 33/326 [00:05<00:49,  5.87it/s]
 10%|████▍                                     | 34/326 [00:05<00:50,  5.77it/s]
 11%|████▌                                     | 35/326 [00:06<00:51,  5.63it/s]
 11%|████▋                                     | 36/326 [00:06<00:54,  5.34it/s]
 11%|████▊                                     | 37/326 [00:06<00:58,  4.97it/s]
 12%|████▉                                     | 38/326 [00:06<00:57,  4.97it/s]
 12%|█████                                     | 39/326 [00:06<00:57,  4.96it/s]
 12%|█████▏                                    | 40/326 [00:07<01:05,  4.37it/s]
 13%|█████▎                                    | 41/326 [00:07<01:11,  3.98it/s]
 13%|█████▍                                    | 42/326 [00:07<01:07,  4.21it/s]
 13%|█████▌                                    | 43/326 [00:07<01:02,  4.51it/s]
 13%|█████▋                                    | 44/326 [00:08<00:59,  4.72it/s]
 14%|█████▊                                    | 45/326 [00:08<00:57,  4.92it/s]
 14%|█████▉                                    | 46/326 [00:08<00:59,  4.69it/s]
 14%|██████                                    | 47/326 [00:08<01:03,  4.38it/s]
 15%|██████▏                                   | 48/326 [00:09<01:02,  4.45it/s]
 15%|██████▎                                   | 49/326 [00:09<00:59,  4.68it/s]
 15%|██████▍                                   | 50/326 [00:09<00:55,  4.99it/s]
 16%|██████▌                                   | 51/326 [00:09<00:57,  4.77it/s]
 16%|██████▋                                   | 52/326 [00:09<00:53,  5.12it/s]
 16%|██████▊                                   | 53/326 [00:09<00:51,  5.29it/s]
 17%|██████▉                                   | 54/326 [00:10<00:48,  5.64it/s]
 17%|███████                                   | 55/326 [00:10<00:43,  6.25it/s]
 17%|███████▏                                  | 56/326 [00:10<00:40,  6.60it/s]
 17%|███████▎                                  | 57/326 [00:10<00:42,  6.39it/s]
 18%|███████▍                                  | 58/326 [00:10<00:44,  5.99it/s]
 18%|███████▌                                  | 59/326 [00:10<00:46,  5.70it/s]
 18%|███████▋                                  | 60/326 [00:11<00:48,  5.49it/s]
 19%|███████▊                                  | 61/326 [00:11<00:50,  5.27it/s]
 19%|███████▉                                  | 62/326 [00:11<00:55,  4.74it/s]
 19%|████████                                  | 63/326 [00:11<01:00,  4.32it/s]
 20%|████████▏                                 | 64/326 [00:11<00:54,  4.80it/s]
 20%|████████▎                                 | 65/326 [00:12<00:51,  5.03it/s]
 20%|████████▌                                 | 66/326 [00:12<00:48,  5.32it/s]
 21%|████████▋                                 | 67/326 [00:12<00:42,  6.07it/s]
 21%|████████▊                                 | 68/326 [00:12<00:42,  6.05it/s]
 21%|████████▉                                 | 69/326 [00:12<00:45,  5.60it/s]
 21%|█████████                                 | 70/326 [00:13<00:51,  4.96it/s]
 22%|█████████▏                                | 71/326 [00:13<00:51,  4.94it/s]
 22%|█████████▎                                | 72/326 [00:13<00:51,  4.93it/s]
 22%|█████████▍                                | 73/326 [00:13<00:51,  4.92it/s]
 23%|█████████▌                                | 74/326 [00:13<00:49,  5.10it/s]
 23%|█████████▋                                | 75/326 [00:14<00:48,  5.22it/s]
 23%|█████████▊                                | 76/326 [00:14<00:50,  4.97it/s]
 24%|█████████▉                                | 77/326 [00:14<00:52,  4.72it/s]
 24%|██████████                                | 78/326 [00:14<00:50,  4.86it/s]
 24%|██████████▏                               | 79/326 [00:14<00:49,  4.97it/s]
 25%|██████████▎                               | 80/326 [00:15<00:48,  5.11it/s]
 25%|██████████▍                               | 81/326 [00:15<00:47,  5.17it/s]
 25%|██████████▌                               | 82/326 [00:15<00:45,  5.34it/s]
 25%|██████████▋                               | 83/326 [00:15<00:44,  5.40it/s]
 26%|██████████▊                               | 84/326 [00:15<00:45,  5.37it/s]
 26%|██████████▉                               | 85/326 [00:15<00:44,  5.42it/s]
 26%|███████████                               | 86/326 [00:16<00:43,  5.48it/s]
 27%|███████████▏                              | 87/326 [00:16<00:39,  6.11it/s]
 27%|███████████▎                              | 88/326 [00:16<00:37,  6.40it/s]
 27%|███████████▍                              | 89/326 [00:16<00:40,  5.82it/s]
 28%|███████████▌                              | 90/326 [00:16<00:43,  5.41it/s]
 28%|███████████▋                              | 91/326 [00:17<00:41,  5.61it/s]
 28%|███████████▊                              | 92/326 [00:17<00:44,  5.29it/s]
 29%|███████████▉                              | 93/326 [00:17<00:47,  4.88it/s]
 29%|████████████                              | 94/326 [00:17<00:46,  5.01it/s]
 29%|████████████▏                             | 95/326 [00:17<00:45,  5.04it/s]
 29%|████████████▎                             | 96/326 [00:18<00:44,  5.22it/s]
 30%|████████████▍                             | 97/326 [00:18<00:42,  5.45it/s]
 30%|████████████▋                             | 98/326 [00:18<00:40,  5.67it/s]
 30%|████████████▊                             | 99/326 [00:18<00:41,  5.49it/s]
 31%|████████████▌                            | 100/326 [00:18<00:41,  5.38it/s]
 31%|████████████▋                            | 101/326 [00:18<00:42,  5.31it/s]
 31%|████████████▊                            | 102/326 [00:19<00:43,  5.20it/s]
 32%|████████████▉                            | 103/326 [00:19<00:41,  5.36it/s]
 32%|█████████████                            | 104/326 [00:19<00:43,  5.12it/s]
 32%|█████████████▏                           | 105/326 [00:19<00:44,  4.94it/s]
 33%|█████████████▎                           | 106/326 [00:19<00:40,  5.50it/s]
 33%|█████████████▍                           | 107/326 [00:20<00:38,  5.63it/s]
 33%|█████████████▌                           | 108/326 [00:20<00:41,  5.31it/s]
 33%|█████████████▋                           | 109/326 [00:20<00:44,  4.87it/s]
 34%|█████████████▊                           | 110/326 [00:20<00:43,  4.95it/s]
 34%|█████████████▉                           | 111/326 [00:20<00:43,  4.99it/s]
 34%|██████████████                           | 112/326 [00:21<00:41,  5.10it/s]
 35%|██████████████▏                          | 113/326 [00:21<00:42,  5.01it/s]
 35%|██████████████▎                          | 114/326 [00:21<00:46,  4.60it/s]
 35%|██████████████▍                          | 115/326 [00:21<00:46,  4.51it/s]
 36%|██████████████▌                          | 116/326 [00:21<00:41,  5.00it/s]
 36%|██████████████▋                          | 117/326 [00:22<00:44,  4.73it/s]
 36%|██████████████▊                          | 118/326 [00:22<00:46,  4.47it/s]
 37%|██████████████▉                          | 119/326 [00:22<00:41,  4.95it/s]
 37%|███████████████                          | 120/326 [00:22<00:39,  5.19it/s]
 37%|███████████████▏                         | 121/326 [00:22<00:39,  5.25it/s]
 37%|███████████████▎                         | 122/326 [00:23<00:41,  4.97it/s]
 38%|███████████████▍                         | 123/326 [00:23<00:41,  4.91it/s]
 38%|███████████████▌                         | 124/326 [00:23<00:36,  5.48it/s]
 38%|███████████████▋                         | 125/326 [00:23<00:35,  5.70it/s]
 39%|███████████████▊                         | 126/326 [00:23<00:34,  5.72it/s]
 39%|███████████████▉                         | 127/326 [00:23<00:34,  5.77it/s]
 39%|████████████████                         | 128/326 [00:24<00:34,  5.74it/s]
 40%|████████████████▏                        | 129/326 [00:24<00:34,  5.71it/s]
 40%|████████████████▎                        | 130/326 [00:24<00:35,  5.60it/s]
 40%|████████████████▍                        | 131/326 [00:24<00:39,  4.94it/s]
 40%|████████████████▌                        | 132/326 [00:25<00:45,  4.25it/s]
 41%|████████████████▋                        | 133/326 [00:25<00:49,  3.92it/s]
 41%|████████████████▊                        | 134/326 [00:25<00:45,  4.20it/s]
 41%|████████████████▉                        | 135/326 [00:25<00:42,  4.52it/s]
 42%|█████████████████                        | 136/326 [00:25<00:38,  4.97it/s]
 42%|█████████████████▏                       | 137/326 [00:26<00:34,  5.53it/s]
 42%|█████████████████▎                       | 138/326 [00:26<00:33,  5.65it/s]
 43%|█████████████████▍                       | 139/326 [00:26<00:30,  6.13it/s]
 43%|█████████████████▌                       | 140/326 [00:26<00:28,  6.54it/s]
 43%|█████████████████▋                       | 141/326 [00:26<00:27,  6.74it/s]
 44%|█████████████████▊                       | 142/326 [00:26<00:28,  6.48it/s]
 44%|█████████████████▉                       | 143/326 [00:26<00:29,  6.22it/s]
 44%|██████████████████                       | 144/326 [00:27<00:30,  5.96it/s]
 44%|██████████████████▏                      | 145/326 [00:27<00:32,  5.60it/s]
 45%|██████████████████▎                      | 146/326 [00:27<00:35,  5.06it/s]
 45%|██████████████████▍                      | 147/326 [00:27<00:37,  4.74it/s]
 45%|██████████████████▌                      | 148/326 [00:28<00:37,  4.80it/s]
 46%|██████████████████▋                      | 149/326 [00:28<00:34,  5.06it/s]
 46%|██████████████████▊                      | 150/326 [00:28<00:31,  5.60it/s]
 46%|██████████████████▉                      | 151/326 [00:28<00:33,  5.22it/s]
 47%|███████████████████                      | 152/326 [00:28<00:37,  4.63it/s]
 47%|███████████████████▏                     | 153/326 [00:29<00:36,  4.70it/s]
 47%|███████████████████▎                     | 154/326 [00:29<00:33,  5.15it/s]
 48%|███████████████████▍                     | 155/326 [00:29<00:33,  5.14it/s]
 48%|███████████████████▌                     | 156/326 [00:29<00:32,  5.22it/s]
 48%|███████████████████▋                     | 157/326 [00:29<00:31,  5.36it/s]
 48%|███████████████████▊                     | 158/326 [00:29<00:31,  5.27it/s]
 49%|███████████████████▉                     | 159/326 [00:30<00:32,  5.06it/s]
 49%|████████████████████                     | 160/326 [00:30<00:36,  4.56it/s]
 49%|████████████████████▏                    | 161/326 [00:30<00:41,  4.02it/s]
 50%|████████████████████▎                    | 162/326 [00:31<00:39,  4.11it/s]
 50%|████████████████████▌                    | 163/326 [00:31<00:37,  4.34it/s]
 50%|████████████████████▋                    | 164/326 [00:31<00:35,  4.53it/s]
 51%|████████████████████▊                    | 165/326 [00:31<00:34,  4.63it/s]
 51%|████████████████████▉                    | 166/326 [00:31<00:32,  4.91it/s]
 51%|█████████████████████                    | 167/326 [00:31<00:28,  5.49it/s]
 52%|█████████████████████▏                   | 168/326 [00:32<00:28,  5.59it/s]
 52%|█████████████████████▎                   | 169/326 [00:32<00:28,  5.53it/s]
 52%|█████████████████████▍                   | 170/326 [00:32<00:27,  5.67it/s]
 52%|█████████████████████▌                   | 171/326 [00:32<00:25,  5.99it/s]
 53%|█████████████████████▋                   | 172/326 [00:32<00:27,  5.70it/s]
 53%|█████████████████████▊                   | 173/326 [00:32<00:28,  5.39it/s]
 53%|█████████████████████▉                   | 174/326 [00:33<00:28,  5.28it/s]
 54%|██████████████████████                   | 175/326 [00:33<00:28,  5.39it/s]
 54%|██████████████████████▏                  | 176/326 [00:33<00:26,  5.56it/s]
 54%|██████████████████████▎                  | 177/326 [00:33<00:30,  4.94it/s]
 55%|██████████████████████▍                  | 178/326 [00:34<00:34,  4.28it/s]
 55%|██████████████████████▌                  | 179/326 [00:34<00:31,  4.62it/s]
 55%|██████████████████████▋                  | 180/326 [00:34<00:32,  4.43it/s]
 56%|██████████████████████▊                  | 181/326 [00:34<00:35,  4.11it/s]
 56%|██████████████████████▉                  | 182/326 [00:34<00:32,  4.37it/s]
 56%|███████████████████████                  | 183/326 [00:35<00:32,  4.44it/s]
 56%|███████████████████████▏                 | 184/326 [00:35<00:29,  4.86it/s]
 57%|███████████████████████▎                 | 185/326 [00:35<00:26,  5.23it/s]
 57%|███████████████████████▍                 | 186/326 [00:35<00:25,  5.55it/s]
 57%|███████████████████████▌                 | 187/326 [00:35<00:24,  5.65it/s]
 58%|███████████████████████▋                 | 188/326 [00:36<00:25,  5.35it/s]
 58%|███████████████████████▊                 | 189/326 [00:36<00:26,  5.18it/s]
 58%|███████████████████████▉                 | 190/326 [00:36<00:25,  5.29it/s]
 59%|████████████████████████                 | 191/326 [00:36<00:26,  5.14it/s]
 59%|████████████████████████▏                | 192/326 [00:36<00:26,  5.05it/s]
 59%|████████████████████████▎                | 193/326 [00:37<00:26,  4.98it/s]
 60%|████████████████████████▍                | 194/326 [00:37<00:26,  4.94it/s]
 60%|████████████████████████▌                | 195/326 [00:37<00:26,  4.94it/s]
 60%|████████████████████████▋                | 196/326 [00:37<00:27,  4.76it/s]
 60%|████████████████████████▊                | 197/326 [00:37<00:29,  4.32it/s]
 61%|████████████████████████▉                | 198/326 [00:38<00:27,  4.73it/s]
 61%|█████████████████████████                | 199/326 [00:38<00:24,  5.16it/s]
 61%|█████████████████████████▏               | 200/326 [00:38<00:23,  5.41it/s]
 62%|█████████████████████████▎               | 201/326 [00:38<00:22,  5.46it/s]
 62%|█████████████████████████▍               | 202/326 [00:38<00:22,  5.54it/s]
 62%|█████████████████████████▌               | 203/326 [00:39<00:22,  5.43it/s]
 63%|█████████████████████████▋               | 204/326 [00:39<00:24,  4.98it/s]
 63%|█████████████████████████▊               | 205/326 [00:39<00:24,  4.93it/s]
 63%|█████████████████████████▉               | 206/326 [00:39<00:24,  4.84it/s]
 63%|██████████████████████████               | 207/326 [00:39<00:26,  4.54it/s]
 64%|██████████████████████████▏              | 208/326 [00:40<00:24,  4.89it/s]
 64%|██████████████████████████▎              | 209/326 [00:40<00:24,  4.82it/s]
 64%|██████████████████████████▍              | 210/326 [00:40<00:24,  4.70it/s]

In [40]:
import json, glob, pandas as pd

results = {}

for f in glob.glob("outputs/*/results.json"):
    with open(f) as fp:
        r = json.load(fp)

    exp = r["experiment_id"]

    results[exp] = {
        "eval_loss": r.get("eval_loss"),
        "train_loss": r.get("train_loss"),
        "wall_clock_min": r.get("wall_clock_minutes"),
        "peak_gpu_mb": r.get("peak_gpu_memory_mb"),
        "data_frac": r.get("data_fraction"),
        "selection": r.get("selection_method"),
        "ordering": r.get("ordering"),
    }

df = pd.DataFrame(results).T.sort_index()

display(df)

df.to_csv("experiments/summary_table.csv")

print(df.to_markdown())

,eval_loss,train_loss,wall_clock_min,peak_gpu_mb,data_frac,selection,ordering
A1,1.204624,1.154256,28.37,6887.5,0.5,adaptive,random
A2,1.204628,1.15426,28.31,6887.5,0.5,adaptive,random
E2,1.195796,1.236928,33.26,6887.6,0.5,random,random
E3,1.204629,1.154256,28.38,6887.5,0.5,adaptive,random
E4,1.204174,1.15427,28.44,6887.5,0.5,adaptive,curriculum
E5,1.195706,1.236344,33.24,6887.6,0.5,random,curriculum

OSError: Cannot save file into a non-existent directory: 'experiments'

In [42]:
%cd /kaggle/working/efficient-llm-finetuning

!echo "=== A1 CONFIG ==="
!cat configs/ablation_diversity_only.yaml

!echo ""
!echo "=== A2 CONFIG ==="
!cat configs/ablation_complexity_only.yaml

/kaggle/working/efficient-llm-finetuning
=== A1 CONFIG ===
# Ablation A1 — diversity-only scoring (β=γ=0, α=1.0)
experiment:
  id: "A1"
  name: "ablation_diversity_only"
  description: "Top-50% selected by diversity score only. Ablates the contribution of the diversity component."

scoring:
  alpha: 1.0
  beta:  0.0
  gamma: 0.0

data:
  selection:
    method: "adaptive"
    fraction: 0.50
  ordering: "random"

training:
  output_dir: "outputs/A1_diversity_only"

seed: 42

=== A2 CONFIG ===
# Ablation A2 — complexity-only scoring (α=γ=0, β=1.0)
experiment:
  id: "A2"
  name: "ablation_complexity_only"
  description: "Top-50% selected by complexity score only. Ablates the contribution of the complexity component."

scoring:
  alpha: 0.0
  beta:  1.0
  gamma: 0.0

data:
  selection:
    method: "adaptive"
    fraction: 0.50
  ordering: "random"

training:
  output_dir: "outputs/A2_complexity_only"

seed: 42

In [52]:
import json
import pandas as pd
import glob
import os

ROOT = "/kaggle/working/efficient-llm-finetuning/efficient-llm-finetuning/efficient-llm-finetuning"

results = {}

for f in glob.glob(os.path.join(ROOT, "outputs", "*", "results.json")):
    with open(f) as fp:
        r = json.load(fp)

    exp = r["experiment_id"]

    results[exp] = {
        "eval_loss": r.get("eval_loss"),
        "train_loss": r.get("train_loss"),
        "wall_clock_min": r.get("wall_clock_minutes"),
        "peak_gpu_mb": r.get("peak_gpu_memory_mb"),
        "data_frac": r.get("data_fraction"),
        "selection": r.get("selection_method"),
        "ordering": r.get("ordering"),
    }

df = pd.DataFrame(results).T.sort_index()

display(df)

print("\n=== MARKDOWN TABLE ===")
print(df.to_markdown())

# Save authoritative summary
os.makedirs(os.path.join(ROOT, "experiments"), exist_ok=True)
df.to_csv(os.path.join(ROOT, "experiments", "summary_table.csv"))

print("\nSaved:")
print(os.path.join(ROOT, "experiments", "summary_table.csv"))

,eval_loss,train_loss,wall_clock_min,peak_gpu_mb,data_frac,selection,ordering
A1,1.204624,1.154256,28.37,6887.5,0.5,adaptive,random
A2,1.204628,1.15426,28.31,6887.5,0.5,adaptive,random
E2,1.195796,1.236928,33.26,6887.6,0.5,random,random
E3,1.204629,1.154256,28.38,6887.5,0.5,adaptive,random
E4,1.204174,1.15427,28.44,6887.5,0.5,adaptive,curriculum
E5,1.195706,1.236344,33.24,6887.6,0.5,random,curriculum

=== MARKDOWN TABLE ===
|    |   eval_loss |   train_loss |   wall_clock_min |   peak_gpu_mb |   data_frac | selection   | ordering   |
|:---|------------:|-------------:|-----------------:|--------------:|------------:|:------------|:-----------|
| A1 |     1.20462 |      1.15426 |            28.37 |        6887.5 |         0.5 | adaptive    | random     |
| A2 |     1.20463 |      1.15426 |            28.31 |        6887.5 |         0.5 | adaptive    | random     |
| E2 |     1.1958  |      1.23693 |            33.26 |        6887.6 |         0.5 | random      | random     |
| E3 |     1.20463 |      1.15426 |            28.38 |        6887.5 |         0.5 | adaptive    | random     |
| E4 |     1.20417 |      1.15427 |            28.44 |        6887.5 |         0.5 | adaptive    | curriculum |
| E5 |     1.19571 |      1.23634 |            33.24 |        6887.6 |         0.5 | random      | curriculum |

Saved:
/kaggle/working/efficient-llm-finetuning/efficient-llm-finetuning/efficient-llm-finetuning/experiments/summary_table.csv

In [54]:
%cd /kaggle/working/efficient-llm-finetuning

!find /kaggle/working -type f -name "train_*.log" -print

/kaggle/working/efficient-llm-finetuning
/kaggle/working/efficient-llm-finetuning/efficient-llm-finetuning/logs/train_20260820_210635.log
/kaggle/working/efficient-llm-finetuning/efficient-llm-finetuning/logs/train_20260820_221919.log
/kaggle/working/efficient-llm-finetuning/efficient-llm-finetuning/efficient-llm-finetuning/logs/train_20260821_004702.log
/kaggle/working/efficient-llm-finetuning/efficient-llm-finetuning/efficient-llm-finetuning/logs/train_20260821_023449.log
/kaggle/working/efficient-llm-finetuning/efficient-llm-finetuning/efficient-llm-finetuning/logs/train_20260821_015642.log
/kaggle/working/efficient-llm-finetuning/efficient-llm-finetuning/efficient-llm-finetuning/logs/train_20260821_030441.log
/kaggle/working/efficient-llm-finetuning/efficient-llm-finetuning/efficient-llm-finetuning/logs/train_20260821_012307.log
/kaggle/working/efficient-llm-finetuning/efficient-llm-finetuning/efficient-llm-finetuning/logs/train_20260821_000443.log

In [61]:
%cd /kaggle/working/efficient-llm-finetuning

!pwd
!git status --short
!git branch --show-current

/kaggle/working/efficient-llm-finetuning
/kaggle/working/efficient-llm-finetuning
?? efficient-llm-finetuning/
main

In [62]:
%cd /kaggle/working/efficient-llm-finetuning/efficient-llm-finetuning

!pwd
!git status --short
!git branch --show-current
!git remote -v

/kaggle/working/efficient-llm-finetuning/efficient-llm-finetuning
/kaggle/working/efficient-llm-finetuning/efficient-llm-finetuning
?? efficient-llm-finetuning/
main
origin	https://github.com/Bezawit-cloud/efficient-llm-finetuning.git (fetch)
origin	https://github.com/Bezawit-cloud/efficient-llm-finetuning.git (push)

In [63]:
%cd /kaggle/working/efficient-llm-finetuning/efficient-llm-finetuning

print("=== CURRENT REPO ===")
!pwd
!ls -la

print("\n=== NESTED DIRECTORY ===")
!ls -la efficient-llm-finetuning

print("\n=== NESTED RESULTS ===")
!find efficient-llm-finetuning -type f -name "results.json" -print | sort

print("\n=== NESTED GIT ===")
!ls -la efficient-llm-finetuning/.git 2>/dev/null || echo "No nested .git"

/kaggle/working/efficient-llm-finetuning/efficient-llm-finetuning
=== CURRENT REPO ===
/kaggle/working/efficient-llm-finetuning/efficient-llm-finetuning
total 64
drwxr-xr-x 12 root root 4096 Aug 21 00:02 .
drwxr-xr-x  9 root root 4096 Aug 20 21:06 ..
drwxr-xr-x  2 root root 4096 Aug 20 21:03 configs
drwxr-xr-x  2 root root 4096 Aug 20 21:07 data
drwxr-xr-x 12 root root 4096 Aug 21 03:52 efficient-llm-finetuning
drwxr-xr-x  8 root root 4096 Aug 21 04:05 .git
-rw-r--r--  1 root root  675 Aug 20 21:03 .gitignore
drwxr-xr-x  2 root root 4096 Aug 20 22:19 logs
drwxr-xr-x  2 root root 4096 Aug 20 21:03 notebooks
drwxr-xr-x  4 root root 4096 Aug 20 21:07 outputs
drwxr-xr-x  2 root root 4096 Aug 20 21:03 paper
-rw-r--r--  1 root root 7110 Aug 20 21:03 README.md
-rw-r--r--  1 root root  567 Aug 20 21:03 requirements.txt
drwxr-xr-x  2 root root 4096 Aug 20 23:32 results
drwxr-xr-x  3 root root 4096 Aug 20 21:04 src

=== NESTED DIRECTORY ===
total 64
drwxr-xr-x 12 root root 4096 Aug 21 03:52 .
drwxr-xr-x 12 root root 4096 Aug 21 00:02 ..
drwxr-xr-x  2 root root 4096 Aug 21 00:02 configs
drwxr-xr-x  2 root root 4096 Aug 21 00:05 data
drwxr-xr-x  2 root root 4096 Aug 21 03:52 experiments
drwxr-xr-x  8 root root 4096 Aug 21 00:44 .git
-rw-r--r--  1 root root  675 Aug 21 00:02 .gitignore
drwxr-xr-x  2 root root 4096 Aug 21 03:04 logs
drwxr-xr-x  2 root root 4096 Aug 21 00:02 notebooks
drwxr-xr-x  9 root root 4096 Aug 21 03:05 outputs
drwxr-xr-x  2 root root 4096 Aug 21 00:02 paper
-rw-r--r--  1 root root 7110 Aug 21 00:02 README.md
-rw-r--r--  1 root root  567 Aug 21 00:02 requirements.txt
drwxr-xr-x  2 root root 4096 Aug 21 01:55 results
drwxr-xr-x  3 root root 4096 Aug 21 00:03 src

=== NESTED RESULTS ===
efficient-llm-finetuning/outputs/A1_diversity_only/results.json
efficient-llm-finetuning/outputs/A2_complexity_only/results.json
efficient-llm-finetuning/outputs/E2_random50_random/results.json
efficient-llm-finetuning/outputs/E3_adaptive50_random/results.json
efficient-llm-finetuning/outputs/E4_adaptive50_curriculum/results.json
efficient-llm-finetuning/outputs/E5_random50_curriculum/results.json

=== NESTED GIT ===
total 56
drwxr-xr-x  8 root root 4096 Aug 21 00:44 .
drwxr-xr-x 12 root root 4096 Aug 21 03:52 ..
drwxr-xr-x  2 root root 4096 Aug 21 00:02 branches
-rw-r--r--  1 root root   36 Aug 21 00:44 COMMIT_EDITMSG
-rw-r--r--  1 root root  282 Aug 21 00:02 config
-rw-r--r--  1 root root   73 Aug 21 00:02 description
-rw-r--r--  1 root root   21 Aug 21 00:02 HEAD
drwxr-xr-x  2 root root 4096 Aug 21 00:02 hooks
-rw-r--r--  1 root root 2118 Aug 21 00:43 index
drwxr-xr-x  2 root root 4096 Aug 21 00:02 info
drwxr-xr-x  3 root root 4096 Aug 21 00:02 logs
drwxr-xr-x  8 root root 4096 Aug 21 00:44 objects
-rw-r--r--  1 root root  112 Aug 21 00:02 packed-refs
drwxr-xr-x  5 root root 4096 Aug 21 00:02 refs

In [64]:
%cd /kaggle/working/efficient-llm-finetuning/efficient-llm-finetuning

!git status --short
!git branch --show-current
!git remote -v

print("\n=== GITIGNORE ===")
!cat .gitignore

/kaggle/working/efficient-llm-finetuning/efficient-llm-finetuning
?? efficient-llm-finetuning/
main
origin	https://github.com/Bezawit-cloud/efficient-llm-finetuning.git (fetch)
origin	https://github.com/Bezawit-cloud/efficient-llm-finetuning.git (push)

=== GITIGNORE ===
# Byte-compiled / optimized / DLL files
__pycache__/
*.py[cod]
*$py.class
*.so

# Environments
.env
.venv
env/
venv/
ENV/
env.bak/
venv.bak/

# Jupyter Notebook checkpoints
.ipynb_checkpoints/
*/.ipynb_checkpoints/*

# Data caches and raw datasets (preserves reproducibility via code)
data/
data/*.json
data/scored_alpaca.json
!data/.gitkeep

# Checkpoint weights and model binaries (keeps repository lightweight)
outputs/
outputs/**/checkpoint-*/
outputs/**/*.safetensors
outputs/**/*.bin
outputs/**/*.pt
outputs/**/*.pth
outputs/**/*.onnx
*.safetensors
*.bin
*.pt

# Execution logs and temporary scratch files
logs/
scratch/
*.log

# OS generated files
.DS_Store
Thumbs.db

In [65]:
print("\n=== CURRENT OUTPUTS ===")
!find outputs -maxdepth 2 -type f -name "results.json" -print | sort

print("\n=== NESTED OUTPUTS ===")
!find efficient-llm-finetuning/outputs -maxdepth 2 -type f -name "results.json" -print | sort

=== CURRENT OUTPUTS ===
outputs/E1_full_baseline/results.json

=== NESTED OUTPUTS ===
efficient-llm-finetuning/outputs/A1_diversity_only/results.json
efficient-llm-finetuning/outputs/A2_complexity_only/results.json
efficient-llm-finetuning/outputs/E2_random50_random/results.json
efficient-llm-finetuning/outputs/E3_adaptive50_random/results.json
efficient-llm-finetuning/outputs/E4_adaptive50_curriculum/results.json
efficient-llm-finetuning/outputs/E5_random50_curriculum/results.json

In [66]:
%cd /kaggle/working/efficient-llm-finetuning/efficient-llm-finetuning

!cp efficient-llm-finetuning/outputs/A1_diversity_only/results.json outputs/A1_diversity_only/results.json
!cp efficient-llm-finetuning/outputs/A2_complexity_only/results.json outputs/A2_complexity_only/results.json
!cp efficient-llm-finetuning/outputs/E2_random50_random/results.json outputs/E2_random50_random/results.json
!cp efficient-llm-finetuning/outputs/E3_adaptive50_random/results.json outputs/E3_adaptive50_random/results.json
!cp efficient-llm-finetuning/outputs/E4_adaptive50_curriculum/results.json outputs/E4_adaptive50_curriculum/results.json
!cp efficient-llm-finetuning/outputs/E5_random50_curriculum/results.json outputs/E5_random50_curriculum/results.json

/kaggle/working/efficient-llm-finetuning/efficient-llm-finetuning
cp: cannot create regular file 'outputs/A1_diversity_only/results.json': No such file or directory
cp: cannot create regular file 'outputs/A2_complexity_only/results.json': No such file or directory
cp: cannot create regular file 'outputs/E2_random50_random/results.json': No such file or directory
cp: cannot create regular file 'outputs/E3_adaptive50_random/results.json': No such file or directory
cp: cannot create regular file 'outputs/E4_adaptive50_curriculum/results.json': No such file or directory
cp: cannot create regular file 'outputs/E5_random50_curriculum/results.json': No such file or directory

In [67]:
%cd /kaggle/working/efficient-llm-finetuning/efficient-llm-finetuning

# Create the missing experiment output directories
!mkdir -p outputs/A1_diversity_only
!mkdir -p outputs/A2_complexity_only
!mkdir -p outputs/E2_random50_random
!mkdir -p outputs/E3_adaptive50_random
!mkdir -p outputs/E4_adaptive50_curriculum
!mkdir -p outputs/E5_random50_curriculum

# Copy the six result files from the nested repository
!cp efficient-llm-finetuning/outputs/A1_diversity_only/results.json outputs/A1_diversity_only/
!cp efficient-llm-finetuning/outputs/A2_complexity_only/results.json outputs/A2_complexity_only/
!cp efficient-llm-finetuning/outputs/E2_random50_random/results.json outputs/E2_random50_random/
!cp efficient-llm-finetuning/outputs/E3_adaptive50_random/results.json outputs/E3_adaptive50_random/
!cp efficient-llm-finetuning/outputs/E4_adaptive50_curriculum/results.json outputs/E4_adaptive50_curriculum/
!cp efficient-llm-finetuning/outputs/E5_random50_curriculum/results.json outputs/E5_random50_curriculum/

/kaggle/working/efficient-llm-finetuning/efficient-llm-finetuning

In [68]:
!find outputs -maxdepth 2 -type f -name "results.json" -print | sort

outputs/A1_diversity_only/results.json
outputs/A2_complexity_only/results.json
outputs/E1_full_baseline/results.json
outputs/E2_random50_random/results.json
outputs/E3_adaptive50_random/results.json
outputs/E4_adaptive50_curriculum/results.json
outputs/E5_random50_curriculum/results.json

In [69]:
import json
import glob

print("=== EXPERIMENT VERIFICATION ===")

for f in sorted(glob.glob("outputs/*/results.json")):
    with open(f) as fp:
        r = json.load(fp)

    print(
        f"{r['experiment_id']}: "
        f"eval_loss={r.get('eval_loss')}, "
        f"train_loss={r.get('train_loss')}, "
        f"selection={r.get('selection_method')}, "
        f"ordering={r.get('ordering')}"
    )

=== EXPERIMENT VERIFICATION ===
A1: eval_loss=1.2046235799789429, train_loss=1.1542556817049807, selection=adaptive, ordering=random
A2: eval_loss=1.2046276330947876, train_loss=1.1542601288909122, selection=adaptive, ordering=random
E1: eval_loss=1.1844764947891235, train_loss=1.2218394773611752, selection=full, ordering=random
E2: eval_loss=1.1957964897155762, train_loss=1.236928045440832, selection=random, ordering=random
E3: eval_loss=1.2046293020248413, train_loss=1.1542563734894589, selection=adaptive, ordering=random
E4: eval_loss=1.2041741609573364, train_loss=1.154269584102334, selection=adaptive, ordering=curriculum
E5: eval_loss=1.1957060098648071, train_loss=1.2363436802681247, selection=random, ordering=curriculum

In [71]:
%cd /kaggle/working/efficient-llm-finetuning/efficient-llm-finetuning

from pathlib import Path

gitignore = Path(".gitignore")
text = gitignore.read_text()

rule = "\n# Keep experiment result metadata under version control\n!outputs/*/results.json\n"

if "!outputs/*/results.json" not in text:
    gitignore.write_text(text.rstrip() + rule)

print(gitignore.read_text())

/kaggle/working/efficient-llm-finetuning/efficient-llm-finetuning
# Byte-compiled / optimized / DLL files
__pycache__/
*.py[cod]
*$py.class
*.so

# Environments
.env
.venv
env/
venv/
ENV/
env.bak/
venv.bak/

# Jupyter Notebook checkpoints
.ipynb_checkpoints/
*/.ipynb_checkpoints/*

# Data caches and raw datasets (preserves reproducibility via code)
data/
data/*.json
data/scored_alpaca.json
!data/.gitkeep

# Checkpoint weights and model binaries (keeps repository lightweight)
outputs/
outputs/**/checkpoint-*/
outputs/**/*.safetensors
outputs/**/*.bin
outputs/**/*.pt
outputs/**/*.pth
outputs/**/*.onnx
*.safetensors
*.bin
*.pt

# Execution logs and temporary scratch files
logs/
scratch/
*.log

# OS generated files
.DS_Store
Thumbs.db
# Keep experiment result metadata under version control
!outputs/*/results.json

In [72]:
# Keep experiment result metadata under version control
!outputs/*/results.json

/bin/bash: line 1: outputs/A1_diversity_only/results.json: Permission denied

In [73]:
from pathlib import Path
import json

ROOT = Path("/kaggle/working/efficient-llm-finetuning/efficient-llm-finetuning")

# Check all 7 JSON files
experiments = [
    "A1_diversity_only",
    "A2_complexity_only",
    "E1_full_baseline",
    "E2_random50_random",
    "E3_adaptive50_random",
    "E4_adaptive50_curriculum",
    "E5_random50_curriculum",
]

for exp in experiments:
    path = ROOT / "outputs" / exp / "results.json"
    print(exp, "→", path.exists())

    if path.exists():
        with open(path) as f:
            r = json.load(f)
        print("   eval_loss:", r.get("eval_loss"))

A1_diversity_only → True
   eval_loss: 1.2046235799789429
A2_complexity_only → True
   eval_loss: 1.2046276330947876
E1_full_baseline → True
   eval_loss: 1.1844764947891235
E2_random50_random → True
   eval_loss: 1.1957964897155762
E3_adaptive50_random → True
   eval_loss: 1.2046293020248413
E4_adaptive50_curriculum → True
   eval_loss: 1.2041741609573364
E5_random50_curriculum → True
   eval_loss: 1.1957060098648071

In [74]:
from pathlib import Path

gitignore = ROOT / ".gitignore"
text = gitignore.read_text()

# Remove any accidentally inserted broken line if present
lines = text.splitlines()
lines = [
    line for line in lines
    if line.strip() != "!outputs/*/results.json"
]

# Add the correct exception
lines.append("")
lines.append("# Keep experiment result metadata under version control")
lines.append("!outputs/*/results.json")

gitignore.write_text("\n".join(lines) + "\n")

print(gitignore.read_text())

# Byte-compiled / optimized / DLL files
__pycache__/
*.py[cod]
*$py.class
*.so

# Environments
.env
.venv
env/
venv/
ENV/
env.bak/
venv.bak/

# Jupyter Notebook checkpoints
.ipynb_checkpoints/
*/.ipynb_checkpoints/*

# Data caches and raw datasets (preserves reproducibility via code)
data/
data/*.json
data/scored_alpaca.json
!data/.gitkeep

# Checkpoint weights and model binaries (keeps repository lightweight)
outputs/
outputs/**/checkpoint-*/
outputs/**/*.safetensors
outputs/**/*.bin
outputs/**/*.pt
outputs/**/*.pth
outputs/**/*.onnx
*.safetensors
*.bin
*.pt

# Execution logs and temporary scratch files
logs/
scratch/
*.log

# OS generated files
.DS_Store
Thumbs.db
# Keep experiment result metadata under version control

# Keep experiment result metadata under version control
!outputs/*/results.json

In [75]:
!git status --short --untracked-files=all

 M .gitignore
?? efficient-llm-finetuning/

In [76]:
%cd /kaggle/working/efficient-llm-finetuning/efficient-llm-finetuning

print("=== Nested repository ===")
!ls -la efficient-llm-finetuning

print("\n=== Nested Git status ===")
!cd efficient-llm-finetuning && git status --short

print("\n=== Outer Git status ===")
!git status --short --untracked-files=all

/kaggle/working/efficient-llm-finetuning/efficient-llm-finetuning
=== Nested repository ===
total 64
drwxr-xr-x 12 root root 4096 Aug 21 03:52 .
drwxr-xr-x 12 root root 4096 Aug 21 00:02 ..
drwxr-xr-x  2 root root 4096 Aug 21 00:02 configs
drwxr-xr-x  2 root root 4096 Aug 21 00:05 data
drwxr-xr-x  2 root root 4096 Aug 21 03:52 experiments
drwxr-xr-x  8 root root 4096 Aug 21 00:44 .git
-rw-r--r--  1 root root  675 Aug 21 00:02 .gitignore
drwxr-xr-x  2 root root 4096 Aug 21 03:04 logs
drwxr-xr-x  2 root root 4096 Aug 21 00:02 notebooks
drwxr-xr-x  9 root root 4096 Aug 21 03:05 outputs
drwxr-xr-x  2 root root 4096 Aug 21 00:02 paper
-rw-r--r--  1 root root 7110 Aug 21 00:02 README.md
-rw-r--r--  1 root root  567 Aug 21 00:02 requirements.txt
drwxr-xr-x  2 root root 4096 Aug 21 01:55 results
drwxr-xr-x  3 root root 4096 Aug 21 00:03 src

=== Nested Git status ===
?? experiments/
?? results/E3_adaptive50_random_results.json
?? results/E4_adaptive50_curriculum_results.json

=== Outer Git status ===
 M .gitignore
?? efficient-llm-finetuning/

In [77]:
print("=== Seven result files ===")
!find outputs -maxdepth 2 -name results.json -print | sort

=== Seven result files ===
outputs/A1_diversity_only/results.json
outputs/A2_complexity_only/results.json
outputs/E1_full_baseline/results.json
outputs/E2_random50_random/results.json
outputs/E3_adaptive50_random/results.json
outputs/E4_adaptive50_curriculum/results.json
outputs/E5_random50_curriculum/results.json

In [78]:
%cd /kaggle/working/efficient-llm-finetuning

!cp -a efficient-llm-finetuning efficient-llm-finetuning_BACKUP

/kaggle/working/efficient-llm-finetuning

In [79]:
%cd /kaggle/working/efficient-llm-finetuning/efficient-llm-finetuning

!rsync -av --exclude='.git/' \
    efficient-llm-finetuning/ \
    ./

/kaggle/working/efficient-llm-finetuning/efficient-llm-finetuning
sending incremental file list
./
.gitignore
README.md
requirements.txt
configs/
configs/README.md
configs/ablation_complexity_only.yaml
configs/ablation_diversity_only.yaml
configs/base_config.yaml
configs/exp1_baseline.yaml
configs/exp2_random50.yaml
configs/exp3_adaptive50_random.yaml
configs/exp4_adaptive50_curriculum.yaml
configs/exp5_random50_curriculum.yaml
data/
data/scored_alpaca.json
experiments/
experiments/summary_table.csv
logs/
logs/data_utils_20260821_000349.log
logs/data_utils_20260821_000445.log
logs/data_utils_20260821_004704.log
logs/data_utils_20260821_012309.log
logs/data_utils_20260821_015644.log
logs/data_utils_20260821_023451.log
logs/data_utils_20260821_030443.log
logs/scoring_20260821_000349.log
logs/scoring_20260821_000450.log
logs/select_and_order_20260821_000516.log
logs/select_and_order_20260821_004709.log
logs/select_and_order_20260821_012314.log
logs/select_and_order_20260821_015649.log
logs/select_and_order_20260821_023457.log
logs/select_and_order_20260821_030448.log
logs/train_20260821_000443.log
logs/train_20260821_004702.log
logs/train_20260821_012307.log
logs/train_20260821_015642.log
logs/train_20260821_023449.log
logs/train_20260821_030441.log
notebooks/
notebooks/cloud_run.ipynb
outputs/
outputs/A1_diversity_only/
outputs/A1_diversity_only/README.md
outputs/A1_diversity_only/adapter_config.json
outputs/A1_diversity_only/adapter_model.safetensors
outputs/A1_diversity_only/chat_template.jinja
outputs/A1_diversity_only/results.json
outputs/A1_diversity_only/tokenizer.json
outputs/A1_diversity_only/tokenizer_config.json
outputs/A1_diversity_only/training_args.bin
outputs/A1_diversity_only/checkpoint-772/
outputs/A1_diversity_only/checkpoint-772/README.md
outputs/A1_diversity_only/checkpoint-772/adapter_config.json
outputs/A1_diversity_only/checkpoint-772/adapter_model.safetensors
outputs/A1_diversity_only/checkpoint-772/chat_template.jinja
outputs/A1_diversity_only/checkpoint-772/optimizer.pt
outputs/A1_diversity_only/checkpoint-772/rng_state.pth
outputs/A1_diversity_only/checkpoint-772/scaler.pt
outputs/A1_diversity_only/checkpoint-772/scheduler.pt
outputs/A1_diversity_only/checkpoint-772/tokenizer.json
outputs/A1_diversity_only/checkpoint-772/tokenizer_config.json
outputs/A1_diversity_only/checkpoint-772/trainer_state.json
outputs/A1_diversity_only/checkpoint-772/training_args.bin
outputs/A2_complexity_only/
outputs/A2_complexity_only/README.md
outputs/A2_complexity_only/adapter_config.json
outputs/A2_complexity_only/adapter_model.safetensors
outputs/A2_complexity_only/chat_template.jinja
outputs/A2_complexity_only/results.json
outputs/A2_complexity_only/tokenizer.json
outputs/A2_complexity_only/tokenizer_config.json
outputs/A2_complexity_only/training_args.bin
outputs/A2_complexity_only/checkpoint-772/
outputs/A2_complexity_only/checkpoint-772/README.md
outputs/A2_complexity_only/checkpoint-772/adapter_config.json
outputs/A2_complexity_only/checkpoint-772/adapter_model.safetensors
outputs/A2_complexity_only/checkpoint-772/chat_template.jinja
outputs/A2_complexity_only/checkpoint-772/optimizer.pt
outputs/A2_complexity_only/checkpoint-772/rng_state.pth
outputs/A2_complexity_only/checkpoint-772/scaler.pt
outputs/A2_complexity_only/checkpoint-772/scheduler.pt
outputs/A2_complexity_only/checkpoint-772/tokenizer.json
outputs/A2_complexity_only/checkpoint-772/tokenizer_config.json
outputs/A2_complexity_only/checkpoint-772/trainer_state.json
outputs/A2_complexity_only/checkpoint-772/training_args.bin
outputs/E2_random50_random/
outputs/E2_random50_random/README.md
outputs/E2_random50_random/adapter_config.json
outputs/E2_random50_random/adapter_model.safetensors
outputs/E2_random50_random/chat_template.jinja
outputs/E2_random50_random/results.json
outputs/E2_random50_random/tokenizer.json
outputs/E2_random50_random/tokenizer_config.json
outputs/E2_random50_random/training_args.bin
outputs/E2_random50_random/checkpoint-772/
outputs/E2_random50_random/checkpoint-772/README.md
outputs/E2_random50_random/checkpoint-772/adapter_config.json
outputs/E2_random50_random/checkpoint-772/adapter_model.safetensors
outputs/E2_random50_random/checkpoint-772/chat_template.jinja
outputs/E2_random50_random/checkpoint-772/optimizer.pt
outputs/E2_random50_random/checkpoint-772/rng_state.pth
outputs/E2_random50_random/checkpoint-772/scaler.pt
outputs/E2_random50_random/checkpoint-772/scheduler.pt
outputs/E2_random50_random/checkpoint-772/tokenizer.json
outputs/E2_random50_random/checkpoint-772/tokenizer_config.json
outputs/E2_random50_random/checkpoint-772/trainer_state.json
outputs/E2_random50_random/checkpoint-772/training_args.bin
outputs/E3_adaptive50_random/
outputs/E3_adaptive50_random/README.md
outputs/E3_adaptive50_random/adapter_config.json
outputs/E3_adaptive50_random/adapter_model.safetensors
outputs/E3_adaptive50_random/chat_template.jinja
outputs/E3_adaptive50_random/results.json
outputs/E3_adaptive50_random/tokenizer.json
outputs/E3_adaptive50_random/tokenizer_config.json
outputs/E3_adaptive50_random/training_args.bin
outputs/E3_adaptive50_random/checkpoint-772/
outputs/E3_adaptive50_random/checkpoint-772/README.md
outputs/E3_adaptive50_random/checkpoint-772/adapter_config.json
outputs/E3_adaptive50_random/checkpoint-772/adapter_model.safetensors
outputs/E3_adaptive50_random/checkpoint-772/chat_template.jinja
outputs/E3_adaptive50_random/checkpoint-772/optimizer.pt
outputs/E3_adaptive50_random/checkpoint-772/rng_state.pth
outputs/E3_adaptive50_random/checkpoint-772/scaler.pt
outputs/E3_adaptive50_random/checkpoint-772/scheduler.pt
outputs/E3_adaptive50_random/checkpoint-772/tokenizer.json
outputs/E3_adaptive50_random/checkpoint-772/tokenizer_config.json
outputs/E3_adaptive50_random/checkpoint-772/trainer_state.json
outputs/E3_adaptive50_random/checkpoint-772/training_args.bin
outputs/E4_adaptive50_curriculum/
outputs/E4_adaptive50_curriculum/README.md
outputs/E4_adaptive50_curriculum/adapter_config.json
outputs/E4_adaptive50_curriculum/adapter_model.safetensors
outputs/E4_adaptive50_curriculum/chat_template.jinja
outputs/E4_adaptive50_curriculum/results.json
outputs/E4_adaptive50_curriculum/tokenizer.json
outputs/E4_adaptive50_curriculum/tokenizer_config.json
outputs/E4_adaptive50_curriculum/training_args.bin
outputs/E4_adaptive50_curriculum/checkpoint-772/
outputs/E4_adaptive50_curriculum/checkpoint-772/README.md
outputs/E4_adaptive50_curriculum/checkpoint-772/adapter_config.json
outputs/E4_adaptive50_curriculum/checkpoint-772/adapter_model.safetensors
outputs/E4_adaptive50_curriculum/checkpoint-772/chat_template.jinja
outputs/E4_adaptive50_curriculum/checkpoint-772/optimizer.pt
outputs/E4_adaptive50_curriculum/checkpoint-772/rng_state.pth
outputs/E4_adaptive50_curriculum/checkpoint-772/scaler.pt
outputs/E4_adaptive50_curriculum/checkpoint-772/scheduler.pt
outputs/E4_adaptive50_curriculum/checkpoint-772/tokenizer.json
outputs/E4_adaptive50_curriculum/checkpoint-772/tokenizer_config.json
outputs/E4_adaptive50_curriculum/checkpoint-772/trainer_state.json
outputs/E4_adaptive50_curriculum/checkpoint-772/training_args.bin
outputs/E5_random50_curriculum/
outputs/E5_random50_curriculum/README.md
outputs/E5_random50_curriculum/adapter_config.json
outputs/E5_random50_curriculum/adapter_model.safetensors
outputs/E5_random50_curriculum/chat_template.jinja
outputs/E5_random50_curriculum/results.json
outputs/E5_random50_curriculum/tokenizer.json
outputs/E5_random50_curriculum/tokenizer_config.json
outputs/E5_random50_curriculum/training_args.bin
outputs/E5_random50_curriculum/checkpoint-772/
outputs/E5_random50_curriculum/checkpoint-772/README.md
outputs/E5_random50_curriculum/checkpoint-772/adapter_config.json
outputs/E5_random50_curriculum/checkpoint-772/adapter_model.safetensors
outputs/E5_random50_curriculum/checkpoint-772/chat_template.jinja
outputs/E5_random50_curriculum/checkpoint-772/optimizer.pt
outputs/E5_random50_curriculum/checkpoint-772/rng_state.pth
outputs/E5_random50_curriculum/checkpoint-772/scaler.pt
outputs/E5_random50_curriculum/checkpoint-772/scheduler.pt
outputs/E5_random50_curriculum/checkpoint-772/tokenizer.json
outputs/E5_random50_curriculum/checkpoint-772/tokenizer_config.json
outputs/E5_random50_curriculum/checkpoint-772/trainer_state.json
outputs/E5_random50_curriculum/checkpoint-772/training_args.bin
outputs/smoke_test/
outputs/smoke_test/smoke_test_results.json
outputs/smoke_test/checkpoint-1/
outputs/smoke_test/checkpoint-1/README.md
outputs/smoke_test/checkpoint-1/adapter_config.json
outputs/smoke_test/checkpoint-1/adapter_model.safetensors
outputs/smoke_test/checkpoint-1/chat_template.jinja
outputs/smoke_test/checkpoint-1/optimizer.pt
outputs/smoke_test/checkpoint-1/rng_state.pth
outputs/smoke_test/checkpoint-1/scheduler.pt
outputs/smoke_test/checkpoint-1/tokenizer.json
outputs/smoke_test/checkpoint-1/tokenizer_config.json
outputs/smoke_test/checkpoint-1/trainer_state.json
outputs/smoke_test/checkpoint-1/training_args.bin
paper/
paper/related_work.md
results/
results/E2_random50_random_results.json
results/E3_adaptive50_random_results.json
results/E4_adaptive50_curriculum_results.json
src/
src/data_utils.py
src/gpu_smoke_test.py
src/scoring.py
src/select_and_order.py
src/train_baseline.py
src/utils.py
src/__pycache__/
src/__pycache__/data_utils.cpython-312.pyc
src/__pycache__/scoring.cpython-312.pyc
src/__pycache__/select_and_order.cpython-312.pyc
src/__pycache__/utils.cpython-312.pyc

sent 681,799,851 bytes  received 3,653 bytes  454,535,669.33 bytes/sec
total size is 681,618,948  speedup is 1.00

In [80]:
!find outputs -maxdepth 2 -type f -name "results.json" -print | sort

outputs/A1_diversity_only/results.json
outputs/A2_complexity_only/results.json
outputs/E1_full_baseline/results.json
outputs/E2_random50_random/results.json
outputs/E3_adaptive50_random/results.json
outputs/E4_adaptive50_curriculum/results.json
outputs/E5_random50_curriculum/results.json

In [81]:
!find experiments -maxdepth 2 -type f -print | sort

experiments/summary_table.csv

In [82]:
!git status --short --untracked-files=all

?? efficient-llm-finetuning/
?? experiments/summary_table.csv
?? results/E2_random50_random_results.json
?? results/E3_adaptive50_random_results.json
?? results/E4_adaptive50_curriculum_results.json

In [83]:
%cd /kaggle/working/efficient-llm-finetuning/efficient-llm-finetuning

print("=== RESULTS JSONS ===")
!find outputs -maxdepth 2 -type f -name "results.json" -print | sort

print("\n=== EXPERIMENT SUMMARY ===")
!find experiments -maxdepth 2 -type f -print | sort

print("\n=== RESULTS DIRECTORY ===")
!find results -maxdepth 2 -type f -print | sort

print("\n=== SOURCE FILES ===")
!find src -type f -print | sort

print("\n=== CONFIG FILES ===")
!find configs -type f -print | sort

/kaggle/working/efficient-llm-finetuning/efficient-llm-finetuning
=== RESULTS JSONS ===
outputs/A1_diversity_only/results.json
outputs/A2_complexity_only/results.json
outputs/E1_full_baseline/results.json
outputs/E2_random50_random/results.json
outputs/E3_adaptive50_random/results.json
outputs/E4_adaptive50_curriculum/results.json
outputs/E5_random50_curriculum/results.json

=== EXPERIMENT SUMMARY ===
experiments/summary_table.csv

=== RESULTS DIRECTORY ===
results/E1_full_baseline_results.json
results/E2_random50_random_results.json
results/E3_adaptive50_random_results.json
results/E4_adaptive50_curriculum_results.json

=== SOURCE FILES ===
src/data_utils.py
src/gpu_smoke_test.py
src/__pycache__/data_utils.cpython-312.pyc
src/__pycache__/scoring.cpython-312.pyc
src/__pycache__/select_and_order.cpython-312.pyc
src/__pycache__/utils.cpython-312.pyc
src/scoring.py
src/select_and_order.py
src/train_baseline.py
src/utils.py

=== CONFIG FILES ===
configs/ablation_complexity_only.yaml
configs/ablation_diversity_only.yaml
configs/base_config.yaml
configs/exp1_baseline.yaml
configs/exp2_random50.yaml
configs/exp3_adaptive50_random.yaml
configs/exp4_adaptive50_curriculum.yaml
configs/exp5_random50_curriculum.yaml
configs/README.md

In [84]:
print("\n=== NESTED GIT CHECK ===")
!test -d efficient-llm-finetuning/.git && echo "NESTED .git EXISTS" || echo "NO NESTED .git"

=== NESTED GIT CHECK ===
NESTED .git EXISTS

In [85]:
%cd /kaggle/working/efficient-llm-finetuning/efficient-llm-finetuning

!rm -rf efficient-llm-finetuning/.git

print("Nested Git metadata removed.")

/kaggle/working/efficient-llm-finetuning/efficient-llm-finetuning
Nested Git metadata removed.

In [86]:
!test -d efficient-llm-finetuning/.git && echo "STILL EXISTS" || echo "OK — nested .git removed"

OK — nested .git removed

In [87]:
!git status --short --untracked-files=all

?? efficient-llm-finetuning/.gitignore
?? efficient-llm-finetuning/README.md
?? efficient-llm-finetuning/configs/README.md
?? efficient-llm-finetuning/configs/ablation_complexity_only.yaml
?? efficient-llm-finetuning/configs/ablation_diversity_only.yaml
?? efficient-llm-finetuning/configs/base_config.yaml
?? efficient-llm-finetuning/configs/exp1_baseline.yaml
?? efficient-llm-finetuning/configs/exp2_random50.yaml
?? efficient-llm-finetuning/configs/exp3_adaptive50_random.yaml
?? efficient-llm-finetuning/configs/exp4_adaptive50_curriculum.yaml
?? efficient-llm-finetuning/configs/exp5_random50_curriculum.yaml
?? efficient-llm-finetuning/experiments/summary_table.csv
?? efficient-llm-finetuning/notebooks/cloud_run.ipynb
?? efficient-llm-finetuning/paper/related_work.md
?? efficient-llm-finetuning/requirements.txt
?? efficient-llm-finetuning/results/E2_random50_random_results.json
?? efficient-llm-finetuning/results/E3_adaptive50_random_results.json
?? efficient-llm-finetuning/results/E4_adaptive50_curriculum_results.json
?? efficient-llm-finetuning/src/data_utils.py
?? efficient-llm-finetuning/src/gpu_smoke_test.py
?? efficient-llm-finetuning/src/scoring.py
?? efficient-llm-finetuning/src/select_and_order.py
?? efficient-llm-finetuning/src/train_baseline.py
?? efficient-llm-finetuning/src/utils.py
?? experiments/summary_table.csv
?? results/E2_random50_random_results.json
?? results/E3_adaptive50_random_results.json
?? results/E4_adaptive50_curriculum_results.json

In [88]:
%cd /kaggle/working/efficient-llm-finetuning/efficient-llm-finetuning

!rm -rf efficient-llm-finetuning

print("Nested duplicate removed.")

/kaggle/working/efficient-llm-finetuning/efficient-llm-finetuning
Nested duplicate removed.

In [89]:
!find outputs -maxdepth 2 -type f -name "results.json" -print | sort

outputs/A1_diversity_only/results.json
outputs/A2_complexity_only/results.json
outputs/E1_full_baseline/results.json
outputs/E2_random50_random/results.json
outputs/E3_adaptive50_random/results.json
outputs/E4_adaptive50_curriculum/results.json
outputs/E5_random50_curriculum/results.json

In [90]:
!git status --short --untracked-files=all

?? experiments/summary_table.csv
?? results/E2_random50_random_results.json
?? results/E3_adaptive50_random_results.json
?? results/E4_adaptive50_curriculum_results.json

In [91]:
%cd /kaggle/working/efficient-llm-finetuning/efficient-llm-finetuning

!git status --short
!git ls-files | head -100

/kaggle/working/efficient-llm-finetuning/efficient-llm-finetuning
?? experiments/
?? results/E2_random50_random_results.json
?? results/E3_adaptive50_random_results.json
?? results/E4_adaptive50_curriculum_results.json
.gitignore
README.md
configs/README.md
configs/ablation_complexity_only.yaml
configs/ablation_diversity_only.yaml
configs/base_config.yaml
configs/exp1_baseline.yaml
configs/exp2_random50.yaml
configs/exp3_adaptive50_random.yaml
configs/exp4_adaptive50_curriculum.yaml
configs/exp5_random50_curriculum.yaml
notebooks/cloud_run.ipynb
paper/related_work.md
requirements.txt
results/E1_full_baseline_results.json
src/data_utils.py
src/gpu_smoke_test.py
src/scoring.py
src/select_and_order.py
src/train_baseline.py
src/utils.py

In [92]:
%cd /kaggle/working/efficient-llm-finetuning/efficient-llm-finetuning

!git add .gitignore
!git add experiments/
!git add results/E2_random50_random_results.json
!git add results/E3_adaptive50_random_results.json
!git add results/E4_adaptive50_curriculum_results.json

/kaggle/working/efficient-llm-finetuning/efficient-llm-finetuning

In [94]:
!git add -f \
    outputs/A1_diversity_only/results.json \
    outputs/A2_complexity_only/results.json \
    outputs/E1_full_baseline/results.json \
    outputs/E2_random50_random/results.json \
    outputs/E3_adaptive50_random/results.json \
    outputs/E4_adaptive50_curriculum/results.json \
    outputs/E5_random50_curriculum/results.json

In [95]:
!git status --short

A  experiments/summary_table.csv
A  outputs/A1_diversity_only/results.json
A  outputs/A2_complexity_only/results.json
A  outputs/E1_full_baseline/results.json
A  outputs/E2_random50_random/results.json
A  outputs/E3_adaptive50_random/results.json
A  outputs/E4_adaptive50_curriculum/results.json
A  outputs/E5_random50_curriculum/results.json
A  results/E2_random50_random_results.json
A  results/E3_adaptive50_random_results.json
A  results/E4_adaptive50_curriculum_results.json

In [96]:
!git diff --cached --stat

 experiments/summary_table.csv                 |  7 +++++++
 outputs/A1_diversity_only/results.json        | 28 +++++++++++++++++++++++++++
 outputs/A2_complexity_only/results.json       | 28 +++++++++++++++++++++++++++
 outputs/E1_full_baseline/results.json         | 28 +++++++++++++++++++++++++++
 outputs/E2_random50_random/results.json       | 28 +++++++++++++++++++++++++++
 outputs/E3_adaptive50_random/results.json     | 28 +++++++++++++++++++++++++++
 outputs/E4_adaptive50_curriculum/results.json | 28 +++++++++++++++++++++++++++
 outputs/E5_random50_curriculum/results.json   | 28 +++++++++++++++++++++++++++
 results/E2_random50_random_results.json       | 28 +++++++++++++++++++++++++++
 results/E3_adaptive50_random_results.json     | 28 +++++++++++++++++++++++++++
 results/E4_adaptive50_curriculum_results.json | 28 +++++++++++++++++++++++++++
 11 files changed, 287 insertions(+)

In [97]:
import json
import glob

print("=== STAGED EXPERIMENT RESULTS ===")

for f in sorted(glob.glob("outputs/*/results.json")):
    with open(f) as fp:
        r = json.load(fp)

    print(
        f"{r['experiment_id']}: "
        f"eval_loss={r.get('eval_loss'):.6f}, "
        f"train_loss={r.get('train_loss'):.6f}"
    )

=== STAGED EXPERIMENT RESULTS ===
A1: eval_loss=1.204624, train_loss=1.154256
A2: eval_loss=1.204628, train_loss=1.154260
E1: eval_loss=1.184476, train_loss=1.221839
E2: eval_loss=1.195796, train_loss=1.236928
E3: eval_loss=1.204629, train_loss=1.154256
E4: eval_loss=1.204174, train_loss=1.154270
E5: eval_loss=1.195706, train_loss=1.236344

In [1]:
!git commit -m "results: add all seven experiment results"

fatal: not a git repository (or any parent up to mount point /kaggle)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).